### ISSUE TITLE
Import like in python?

### ISSUE THREAD

**Issue by dkrikun** [textX/textX#103]
Hello,

I would like to have an import mechanics similar to python. In particular, I would like to have the imported module name act as a namespace. For example:

```
# imported module 'base.mod'
class a {};
```

```
# main module
import 'base.mod'
var x = new base.a()
```
So I've put the 'ImportFQN' provider for '*.*', but the name is still resolved as 'a' and not 'base.a'.
I do not understand what the FQN providers consider for valid prefixes when resolving a name.

Related to this, could be nice to be able to do something like `import x.y.z as w`, is it possible?

Thanks :smile:

**Comment by goto40** [comment]
At the moment all includes are flat. The current importuri scope providers
are not capable of fulfilling your needs.

I see different possibilities of introducing your requirements into the
scope provider design. I would like to take my time to write them down and
to discuss them.

Thank you for the idea.

Note: the rule containing the importuri field contains also the imported
model. With a custom scope provider, this should allow to implement an
appropriate scope provider. See:
http://www.igordejanovic.net/textX/stable/scoping/ ("Model objects formed
by the rules with an importURI attribute get an additional attribute
_tx_loaded_models which is a list of the loaded models by this rule
instance.").

(to be continued)

Am Mi., 14. Nov. 2018, 09:48 hat Daniel Krikun <notifications@github.com>
geschrieben:

**Comment by goto40** [comment]
I think it is not so difficult. As mentioned in the note above, nearly all information is available. I will setup a unittest to clarify the needs and make a small demo. We can discuss it then...

In particular:
  * Import "folder_a/folder_b/file.ext" --> import folder_a.folder_b.file (hook to transform an importUri string to a filename)
  * import "file" as name (references relative to the import object)

**Comment by goto40** [comment]
Check #106
To be discussed... But I think your wishes were quite clear and the problem to be solved is unambiguous.

**Comment by goto40** [comment]
(sorry - reopened, closed issue by accident)

**Comment by goto40** [comment]
(not fully finished - I try your example)

**Comment by goto40** [comment]
I integrated your example above (without the "import as" like in "import xy as ab"). 

"Import as" is covered in the unittests.

**Comment by dkrikun** [comment]
awesome :blush:
