### ISSUE TITLE
Object processor with imports

### ISSUE THREAD

**Issue by dkrikun** [textX/textX#108]
I have a scoping provider `PlainNameImportURI`, with two files `a.dsl` and `b.dsl`:

```
import 'b.dsl';
class A {}
```

```
class B {}
```

I register a model processor and an object processor for the class object. Then I observe that model processor callable is called as expected, but object processors are called twice for each object (that is 4 times in the example above, 2 for each 'class'). Also I see that they are only called while processing the main model (the one that imports).

The code looks like this:
```python
def print_obj(x):
    print(x.name)

def print_model(m, mm):
    print(m._tx_filename)

mm.register_scope_providers({'*.*', scoping_providers.PlainNameImportURI()}
mm.register_obj_processors({'Class': print_obj})
mm.register_model_processor(print_model)
```

The output is then:
```
b.dsl
A
B
A
B
a.dsl
```

I'm using textX from pypi, version 1.8.0

Is it expected? I would expect to see:
```
B
b.dsl
A
a.dsl
```

**Comment by goto40** [comment]
You are really digging for the details! That is great!!!!
I need some time to have a look at this... It looks like a bug (Postponed for the moment - wait some days)

Thank you very much!

**Comment by goto40** [comment]
see #118
