### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by dkrikun** [textX/textX#110]
I wanted to hack a bit on textX, so I've cloned master, and I've run the tests before doing anything, and there are a few fails, there, is it expected?

[pytest_out.txt](https://github.com/igordejanovic/textX/files/2591662/pytest_out.txt)

**Comment by igordejanovic** [comment]
No, it is not :). 

It seem to be a cross-platform path construction issue. Path constructions should use `os.path.join` instead of hard coding path separator. Thanks for the report.

**Comment by goto40** [comment]
issue resolved (see #106 "all green")
