### ISSUE TITLE
Transfering textX and related projects under textX organization

### ISSUE THREAD

**Issue by igordejanovic** [textX/textX#122]
I'm thinking for quite some time about this as the project has many contributors now and I'm not a sole maintainer anymore this seems to make sense. The additional benefit is to transfer related textX tools (IDE plugins, language server, visualizators) which are currently hosted [here](https://github.com/textx-tools) under a single organization and thus make them more visible.

I've never done this before so thinking about consequences in terms of project being on the different URL. 
I've read [this](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) and [this](https://help.github.com/articles/about-repository-transfers/) and according to the docs the transition should go smooth but still not sure would there be any problem. Any input on this is appreciated.

**Comment by goto40** [comment]
I have no experience with this topic. I think we can just try it...

Maybe make an announcement when the migration takes place... 

We will need to fix links in the docu. Possibly in the issues as well...

**Comment by igordejanovic** [comment]
Ok. I guess all meta-data will remain so all we should care about would be links although a redirection will be configured so we can gradually correct all links in the docs. I will announce here when the migration is planed.

**Comment by igordejanovic** [comment]
I've started to transfer some of the textX related project to textX organization. So far so good.

**Comment by igordejanovic** [comment]
If I don't encounter any problem in the meantime the transfer will happen by the end of the next week.
I'll post the details soon.

**Comment by goto40** [comment]
Is it safe to work on pull request #133 the next days? Should I wait until the transfer is completed?

**Comment by igordejanovic** [comment]
The transfer will take place on 27th December.

**Comment by igordejanovic** [comment]
Transfer completed. `textX` organization is now a new home for this project.

If you have a local clone of this repo you can clone again or update your git remote:
```
git remote set-url origin git@github.com:textX/textX.git
```
or for https protocol:
```
git remote set-url origin https://github.com/textX/textX.git
```

**Comment by igordejanovic** [comment]
The docs is now hosted at http://textx.github.io/textX/

Please update your bookmarks.

**Comment by approxit** [comment]
[Some links](https://github.com/textX/textX/search?q=igordejanovic&unscoped_q=igordejanovic) in docs are still pointing to personal namespace and not textx organization.

**Comment by goto40** [comment]
I will adapt the links now

**Comment by goto40** [comment]
links fixed
