### ISSUE TITLE
Suggestion to change the current choice (`readthedocs`) for mkdocs theme for better readability

### ISSUE THREAD

**Issue by simkimsia** [textX/textX#143]
I am going through the tutorial now.

In the HelloWorld I mistake the comma for a period.

I like to recommend switching the theme to something that makes the code syntax highlighting more readable. 

Not sure if it's possible, but I saw a free theme for Guzzle http://www.writethedocs.org/guide/tools/sphinx-themes/#guzzle-theme

and I checked out their website, and at least the comma is quite obvious. 

http://docs.guzzlephp.org/en/stable/

What does the community think?

## Update

I think guzzle is a purely sphinx theme and does not have a mkdocs theme equivalent. So ignore my recommendations

**Comment by Aluriak** [comment]
Mistaking the comma for a period sounds like a font problem, rather than a highlighting one.

If it's possible to change something about that, i recommend something like Source code pro or Monoid.

**Comment by igordejanovic** [comment]
textX uses [MkDocs](https://github.com/mkdocs/mkdocs) for the docs together with [mike](https://github.com/jimporter/mike) for versioning (see the version change control in the upper left corner of the docs).

@simkimsia You could try to experiment with mkdocs themes. You can do that locally by changing [mkdocs.yml file](https://github.com/igordejanovic/textX/blob/master/mkdocs.yml). If you find something that you think would be better visually post here so we can discuss. Please note that it must support mike or at least it could be easily adapted.

As @Aluriak said, if it is only a problem with comma/period problem we could change the font.

**Comment by simkimsia** [comment]
It's a font issue. Let me experiment with mkdocs themes first. I'll report my findings here.

**Comment by simkimsia** [comment]
Sorry, I'm really noob at this. So I have forked textX and do I need to follow the instructions here https://docs.readthedocs.io/en/latest/install.html and install readthedocs locally in order to test a suitable theme?

Which Python version do I use to be compatible with the readthedocs for textX?

**Comment by igordejanovic** [comment]
Follow the [contribution guide](https://github.com/igordejanovic/textX/blob/master/CONTRIBUTING.md) to setup your environment.

After that you will be able to run mkdocs server from the root folder of the project:
```
mkdocs serve
```

You will see the local address where you can access the docs from the browser.
Go to the MkDocs site and see what themes are available with the default MkDocs install and play with `mkdocs.yml` settings. After each change to the .yml file you will have to stop mkdocs server and start it again.

You should be ok with any recent Python version.

**Comment by igordejanovic** [comment]
BTW, we are just using `readthedocs` inspired theme from MkDocs. It has nothing to do with readthedocs site.

**Comment by simkimsia** [comment]
Okay took me a while to learn that there were two builtin themes for mkdocs : `mkdocs` and `readthedocs`

## No change. Stick to `readthedocs` 

<img width="836" alt="image" src="https://user-images.githubusercontent.com/245021/50391966-01938280-0785-11e9-8207-586b8e4ff9c2.png">

Pros:

- built in, so only need to make 1 change in the `mkdocs.yml`

Cons:

 - Same code screenshot as mkdocs screenshot. As u can see, the `comma` is not as obvious in the code highlight.

## Keep `readthedocs` but change the font family to `source code pro` for `code` inside `style.css`

![image](https://user-images.githubusercontent.com/245021/50392420-3dc8e200-0789-11e9-9c39-898c2812e49a.png)

Pros:

- looks good for the code syntax (see above) comma is now obvious
- Keep the original `readthedocs` theme

Cons:

- not really except that need to add one line of css in `styles.css`

## Switch to `mkdocs`

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/245021/50391956-e759a480-0784-11e9-9dce-9efbfd7321ad.png">

Pros:

- solve the code highlight issue for the comma
- built in, so only need to make 1 change in the `mkdocs.yml`

Cons:

 - `mkdocs` theme has a weakness where the hierarchy can only show two levels deep in the navigation menu though the font style for the code highlight is way better.


## 3rd party themes - alabaster

![image](https://user-images.githubusercontent.com/245021/50392216-63ed8280-0787-11e9-80b6-27a1a87533e6.png)

Pros:

- looks good for the code syntax (see above)
- same as the one used by major Python libraries such as https://www.paramiko.org/index.html and pyinvoke
- default theme of sphinx

Cons:

- this is a port of alabaster for mkdocs
- may need to customize code for the navigation menu for this port of alabaster
- because this is 3rd party theme (and not builtin) need to add more files in order for the theme to work.



@igordejanovic @Aluriak Let me know what you guys think. There are more 3rd party themes, but I think just go with the default readthedocs with the change in the font family for code as per @Aluriak  suggested for now.

If all agree, I will send a PR to change the settings in the `mkdocs.yml`. If you want me to explore more 3rd party themes, let me know.

**Comment by igordejanovic** [comment]
Thanks for the detailed analysis. I think we should stick with the provided builtin themes unless there is a compelling reason not to. I vote for font change and keeping the current theme. 
That solves readability issue without introducing any disturbance. 

Furthermore, I was experimenting in the past with readthedocs site, and there is still textX docs there (although some older version). I wasn't pleased at that time that RTD supported only sphinx with ReST syntax (which I don't like very much) so I choose to use MkDocs and host it on GitHub pages under my personal domain. We might consider again moving the docs to readthedocs site if there is support now for markdown.

**Comment by Aluriak** [comment]
Agree with the standard styling and font change.

**Comment by simkimsia** [comment]
>We might consider again moving the docs to readthedocs site if there is support now for markdown.

I have created an issue #150 regarding this.
