### ISSUE TITLE
Is it a good idea to gitignore the dot files generated by the `textX visualize` command?

### ISSUE THREAD

**Issue by simkimsia** [textX/textX#145]
I didn't post this in SO because it might be a subjective question. So I am posting it here. Thank you.

**Comment by igordejanovic** [comment]
It usually is as it is a product of code generation/compilation so you treat them as you would treat e.g. Python `.pyc` files or Java `.class` files. You don't keep them in version control as you can always regenerate when needed. And you usually want to get some other form anyway (.png, .pdf) so .dot are just transient files.

But, if it is a part of the docs for example, and that documentation system is able to render .dot files directly somehow then yes, they should be kept in the version control like you would keep .png, .jpg or .pdf even those are generated.

**Comment by simkimsia** [comment]
Copy that. Thanks! Grateful for the clear answer :)
