### ISSUE TITLE
Please read this before asking questions

### ISSUE THREAD

**Issue by igordejanovic** [textX/textX#147]
We are changing the venue for support questions about textX. For a discussion see #139.

From now on, please ask questions on [StackOverflow](https://stackoverflow.com/questions/tagged/textx/).
Just make sure to use `textx` tag so we could notice it.

Issue tracker will be used for bugs, feature requests and suggestions.

**Comment by approxit** [comment]
Actually [discuss page on docs](http://textx.github.io/textX/stable/about/discuss/) is missing this hint :)

**Comment by igordejanovic** [comment]
@approxit Good catch. Thanks. Actually, discuss page is redundant as the correct info is available on the index page. Removed discuss page.

**Comment by igordejanovic** [comment]
We are moving all questions and discussions to Discussions #325
