### ISSUE TITLE
ModuleNotFoundError: No module named 'textx' when running functional tests

### ISSUE THREAD

**Issue by simkimsia** [textX/textX#149]
I followed this comment https://github.com/igordejanovic/textX/issues/143#issuecomment-449556703 and at the step where I run `py.test tests/functional` at step 3 of https://github.com/igordejanovic/textX/blob/master/CONTRIBUTING.md#get-started

I get `no module named 'textx' error`. However, when I type `textx` it is definitely installed.

**Comment by igordejanovic** [comment]
You should ask support questions on SO :)

**Comment by igordejanovic** [comment]
But this might be bug in the contribution guide. Will check during the day.

**Comment by igordejanovic** [comment]
Checked and it works fine. Seems that contribution guide is ok.

**Comment by goto40** [comment]
Sometimes it helps to define 'PYTHONPATH=.' (export PYTHONPATH=.) before running the tests.

**Comment by simkimsia** [comment]
>You should ask support questions on SO :)

Right, I apologise. will duplicate the question there and close this.

`export PYTHONPATH=.` this works and I only need to do it once. I would like to know why I need this.

I have created the SO question and the [answer](https://stackoverflow.com/a/53913739/80353) as a community wiki. So I believe anybody can edit the answer.
