### ISSUE TITLE
A way to integrate new textX CLI subcommands

### ISSUE THREAD

**Issue by igordejanovic** [textX/textX#161]
Related to #148 #42 

See the initial discussion [here](https://github.com/textX/textX/issues/148#issuecomment-456643632).

The idea would be to provide an extension point for new sub-commands. In that way `textx` cli could be extended by new sub-commands by both official and un-official projects installable using `pip`.

See how it is done in the [textx-tools](https://github.com/textX/textx-tools/blob/master/setup.py#L59) project with `list-gens` and `list-langs` commands. For example [this](https://github.com/textX/textx-tools/blob/master/txtools/gen.py#L12).

**Comment by igordejanovic** [comment]
@danixeee [asked](https://github.com/textX/textX/issues/148#issuecomment-456804572):
> Do we want to extend textx CLI with textX-LS-core subcommands or we should keep them separate?

I think that it is easier for a user to remember just one command `textx` and then query it for further sub-commands. It is prevailing way of work with contemporary complex tools (think `git` for example). LS sub-commands could be grouped under e.g. `ls` sub-command (`textx ls some_command...`).

**Comment by danixeee** [comment]
I can't extend textX CLI with sub-command. Here is core [setup.py](https://github.com/textX/textX-LS/blob/danixeee/textxfile-lang-support/textX-LS/core/setup.py#L45). I have defined `textx-ls` CLI to check if `langs` command is working.

Here are some pictures:

![image](https://user-images.githubusercontent.com/16227576/51702039-0f058c00-2013-11e9-9cfb-ebdec2f43cd3.png)

![image](https://user-images.githubusercontent.com/16227576/51702065-1dec3e80-2013-11e9-8783-29e2465e75b1.png)

I have installed `textx_ls_core` package with `pip install -e .`, also I have tried to build a wheel and install package from it - without success.

@igordejanovic Am I missing something?

**Comment by igordejanovic** [comment]
There is no support for extending textX CLI commands in textX yet. I'll work on it in the following days.

**Comment by danixeee** [comment]
I was looking at `textX-tools` project, I don't know why I thought that `textX` is using it for CLI.
