### ISSUE TITLE
Reference of create

### ISSUE THREAD

**Issue by aranega** [textX/textX#167]
Hi @igordejanovic, 

I was playing with textX and its wonderfu reference system, and I wonder if it is possible to have a rule reference that creates the object first if it does not find it (e.g, like in dot or plantUML). I know that could lead to a mess in the produced model, but I wonder if it currently exists a way of performing such a trick.

Thanks!

**Comment by igordejanovic** [comment]
Hi @aranega.
I believe this could be done by implementing a custom scope provider that would search the model for the given reference and create the object if is none is found. 
Please see [the docs](http://textx.github.io/textX/stable/scoping/).

This part is done by @goto40 so maybe he could give you a hint?

**Comment by aranega** [comment]
@igordejanovic Thanks so much for the pointer, I was sure that I was missing something!

**Comment by goto40** [comment]
I created an example. However, I see some limits. The example will, thus, not work in more complicated scenarios. There, you may need to return a "Postponed" for other lookups for persons, which do not find their reference (since the reference *may* be defined by a later lookup). See #168

**Comment by goto40** [comment]
With this change, we overcome the problem when referencing objects invented by another lookup (in the future) with our postponed mechanism. See example and the docu in the test.

**Comment by aranega** [comment]
Thanks a lot @goto40 . I will play with that today. For my scenario it should be enough. The idea is to bridge plantUML syntax with pyuml2 (UML2 implementation in Python). I'm sure it should be enough! Thanks again!
