### ISSUE TITLE
Preparing release v2.0.0

### ISSUE THREAD

**Issue by igordejanovic** [textX/textX#171]

**Comment by goto40** [comment]
What has to be done for 2.0.0?

**Comment by igordejanovic** [comment]
I guess we should resolve pending PRs (at least what is possible at the moment) and update CHANGELOG with note on all backward incompatible changes.
There is a lot of your work in the pending PRs so I must run through all of those and see what is ready. I will look into it in the following days.

**Comment by goto40** [comment]
Understood. Ok.

**Comment by zilakmarian** [comment]
Will v2.0.0 support python2.7 or are there plans on dropping python2 compatibility?

**Comment by igordejanovic** [comment]
@zilakmarian There are no plans for dropping Python 2 support yet. We will support it as long as there is a support in the tools we are using for development/testing. 

v2.0.0 will be just a start of using semantic versioning where we'll increase major version number with each backward incompatible change. So expect that major versions will increase much faster now, but it should be safe to do upgrades with each minor version change as it shouldn't introduce any backward incompatible change. This way we are better communicating when users should pay attention to the CHANGELOG to see what changes are necessary during upgrade.
