### ISSUE TITLE
Language registration/discovery

### ISSUE THREAD

**Issue by igordejanovic** [textX/textX#175]
I'm starting this discussion as we are in a growing need of organizing multiple
languages/meta-models in a consistent way.

There was [the project](https://github.com/textX/textx-tools) that meant to deal
with the problem of consistent organization/registration and discovery of
languages and compiler/generators. The project has been dormant for a longer
time now and I think it is the time to revive the discussion and see what would
be the proper way to handle this.

What we need is a way to:

-   Register language with its name, file extension and the description
-   Once registered language should be discoverable and meta-model instance should
    be easily retrievable

@goto40 `validate` command from the example is very similar to the current textx
`check` command but done without access to the grammar. With language
registration it would be fairly easy to make `validate` command generic. The
proper language could be selected by the extension or given explicitly to
override the extension.

Something like:

    textx validate --language flow *.flow

In the same way textX grammar could be validated as it is nothing more but a
model written in textX language which should be built-in.

    textx validate flow.tx
    # or
    textx validate --language textx flow.tx

Like it was done in [the old project](https://github.com/textX/textx-tools) we shall have a way to list all the
language with its registered names, extensions and descriptions:

    $ textx list-languages
    textx (tx)    textX grammars
    robot (rbt)   A language for moving robot in a grid
    flow (flow)   A language for description of data processing flow
    ...

Now, compiler/code generator can also be registered in the core. Each generator
should provide the name of the language it is generator for, its name (id), the
description, and the callable that would carry out code generation during
registration.

All registered generators could be listed:

    $ textx list-generators
    flow-python          Generating Python code for flow models
    flow-java            Generating Java code for flow models
    flow-PlantUML        Generating PlantUML visualization for flow models
    robot-java           Generating Java code for Robot models
    robot-django         Generating Django web application for Robot models

Generator can be called on the model(s) for a given language. 

Something like:

    textx generate flow-python <output-folder> *.flow

One nice thing to note is that current `visualize` command is nothing more but a
code generator for textX language and dot/PlantUML output.

@danixeee The additional benefit is that textX-LS integration should be even
simpler as the core language information is provided by the textX itself and
only LS specific stuff should be provided by the current `LanguageTemplate`
inherited class.

This is just some initial brain-dump and surely would require some polishing.

Thoughts?

**Comment by goto40** [comment]
First, I like the ideas you sketched above very much!!

The following points come to my mind:

 * Extension conflicts should pose no problem, since the language itself is specified as well. Note, that the MetaModelProvider cannot take the role of managing the extension-to-language mapping: extension conflicts could break multi-metamodel logic... (?) 

 * For an editor or workbench we could have nice GUI switches to select, e.g., the generators.

 * however, I hope textX does not give up its ability of being light weight... 

For me, handling **name clashes** for language names (maybe also extensions) is a central question... 

Of course one could say, that name clashes for python modules are not an issue, so why should there be an issue for language names? I do not know... I just see that a language names like "flow", "message", "types" will be very common...

**Comment by goto40** [comment]
I like the idea of the common **validate command** (except from my name clash thoughts).

I just played around with a simple Tk-Treeview of a model. This would also be a possible common command: **inspect model**.

As you mentioned, all the exports would just be (generic) code generators. I like this idea very much...

**Comment by igordejanovic** [comment]
> Extension conflicts should pose no problem, since the language itself is specified as well. Note, that the MetaModelProvider cannot take the role of managing the extension-to-language mapping: extension conflicts could break multi-metamodel logic... (?) 

If you mean file extensions as they might be non-unique, you are right, that's why there should be a language name provided which is a unique ID. In all commands and APIs if the name is not provided it is deduced from the file extensions but if there are multiple languages with the same file extensions an exception should be raised and the language name should be provided in that case.

Furthermore I was thinking about introducing `import` syntax extension to support meta-model references:

```
import lang:types

MyProp:
    `prop` name=ID ':' type=[types.Type]
```

or with aliasing:

```
import lang:types as t

MyProp:
    `prop` name=ID ':' type=[t.Type]
```

`import` is extended to allow not only grammar import but importing of registered languages.

In this way we are introducing dependency to other language at the grammar/metamodel level and we are explicit which `Type` we are referring to so, for example, my grammar might also have a rule `Type` defined but I'm making explicit which one I'm referring to. This will make setting up meta-models easier and more straightforward.

I have some other ideas about language extensibility/composability but this stuff should be discussed in another issue.

> For an editor or workbench we could have nice GUI switches to select, e.g., the generators.

Yes, both languages and generators would be easily discoverable by both CLI tools and IDEs.

> however, I hope textX does not give up its ability of being light weight... 

Sure, that is one of the most compeling properites of textX and we won't leave that. I think this language registration is a nice addition which will make things easier for tool developers and users and won't change the way textX works now. You can still decide not to register your language and use it as before. Also, I think that the implementation should be relatively simple.

> For me, handling **name clashes** for language names (maybe also extensions) is a central question... 
> Of course one could say, that name clashes for python modules are not an issue, so why should there be an issue for language names? I do not know... I just see that a language names like "flow", "message", "types" will be very common...

I believe that going with the requirement that name should be unique but file extension should not be (although, it would be advisable to be) is enough to prevent problems.
You are right that there might be created languages with the same name but still you can install only those you want in your Python virtualenv. So the problem really boils down to the same problem Python packages have.

> I just played around with a simple Tk-Treeview of a model. This would also be a possible common command: **inspect model**.

Yes, that would be really cool to have. A simple model explorer :)

**Comment by danixeee** [comment]
I like the idea. I have already implemented some of those stuff in [textX-LS-core](https://github.com/textX/textX-LS/tree/danixeee/language-installation-mechanism/textX-LS/core) project, but it does make sense to move it to `textX`.

![image](https://user-images.githubusercontent.com/16227576/55276365-54845500-52f3-11e9-80e9-b3b6a4966bdb.png)

Based on a file extension, appropriate grammar is used. Currently it does not support having languages with the same file extensions.

> textx validate --language flow *.flow

I guess it is enough to just call `textx validate --language flow`, because `flow` language can have different file extensions and if we want to validate _all_ model files, we can just let _textX_ find all "model files".

I just went through _LSP_ again to see what params are passed [when a file is opened](https://microsoft.github.io/language-server-protocol/specification#textDocument_didOpen). 

```
interface TextDocumentItem {
	/**
	 * The text document's URI.
	 */
	uri: DocumentUri;

	/**
	 * The text document's language identifier.
	 */
	languageId: string;

	/**
	 * The version number of this document (it will increase after each
	 * change, including undo/redo).
	 */
	version: number;

	/**
	 * The content of the opened text document.
	 */
	text: string;
}
``` 

So, based on _languageId_, instead of file extension (how it works now), we will know which language template to use. I will investigate more, how VS Code selects a language based on a file extension, if there are same file extensions for different languages..

**Comment by igordejanovic** [comment]
> I like the idea. I have already implemented some of those stuff in textX-LS-core project, but it does make sense to move it to textX.

I don't think we should replace LS registration/support. The LS specific stuff should remain registed in `textxls_langs` EP. I just wan't to move pure generic language stuff to the textX so that we get all the benefits from the CLI, while LS support could provide LS stuff (e.g. code completion, outline etc.). For example, instantiating meta-model for the given language should be handled by textX as it can be used in different, LS-unrelated, scenarios.

> I guess it is enough to just call `textx validate --language flow`, because `flow` language can have different file extensions and if we want to validate _all_ model files, we can just let _textX_ find all "model files".

You still have to give the model (or set of models) to the `validate` command. I would make that explicit. The idea is to use `textx validate *.flow` when there is only a single language with `flow` file extension registered (if we allow that there can be more). If there are more than one language than you must provide `--language flow` where `flow` in this case is the name of the language.


BTW, why do you think that a single language could have multiple file extensions? I think that would complicate matters without any benefit I could think of.

> So, based on languageId, instead of file extension (how it works now), we will know which language template to use. 

Yes, `languageId` (aka `name`) is unique. But when opening a file in the editor the only info you have is the file extension, so you could e.g. try to parse with all languages registered for that extension and take first that succeed (not ideal but possible solution).

> I will investigate more, how VS Code selects a language based on a file extension, if there are same file extensions for different languages..

Great!

**Comment by danixeee** [comment]
> I don't think we should replace LS registration/support. The LS specific stuff should remain registed in textxls_langs EP.

Should I wait with my [issue](https://github.com/textX/textX-LS/issues/12) until this task is completed and see how can I combine _textX_ and _textX-LS_ to support language installation from VS Code? Or I will switch to try if I can programmatically (un)install extensions without restarting VS Code instance.

> BTW, why do you think that a single language could have multiple file extensions? I think that would complicate matters without any benefit I could think of.

I guess I was looking at VS Code's manifest `package.json` file and saw that they support multiple file extension for the same language (see [this](https://github.com/textX/textX-LS/blob/danixeee/language-installation-mechanism/client/package.json#L57)). Probably we won't need it.

**Comment by igordejanovic** [comment]
> Should I wait with my issue until this task is completed and see how can I combine textX and textX-LS to support language installation from VS Code? 

You can look at #177 as the basic idea is layouted so we can work together on aligning textX core and textX-LS. I plan to write somes test tomorrow and try to rework some of the existing textX commands. (Un)installing extensions in VS Code without restart would be really cool but I don't think it is crucial at this point.

**Comment by danixeee** [comment]
@igordejanovic I have implemented an initial VS Code extension generator which uses grammar file and produces `.vsix` file. Can we pass (and does it make sense) additional data to generators (see [this](https://github.com/danixeee/textx-gen-vscode/blob/master/textx_vscode_gen/__init__.py#L35))? 

EDIT: I am using hardcoded syntax file, because my plan is to have another generator which will know how to generate syntax file(s) (in this case textmate json file), for e.g.:

```bash
textx generate workflow.tx --target=textmate-syntax
```

but since I will use it from _textx_vscode_gen_ I will run it from python code:

```python
from textx import generator_for_language_target
gen = generator_for_language_target('textx', 'textmate-syntax'
# call gen
```

Does that make sense to you, too?

**Comment by igordejanovic** [comment]
> Can we pass (and does it make sense) additional data to generators (see this)?

I guess we should pass additional, generator-specific, data. I'm investigating possible approaches.
BTW, I'm in the process of changing the signature of the generator callables slightly to pass in the meta-model and the `debug` flag.

> Does that make sens to you, too?

Yes, it makes perfect sense.

**Comment by igordejanovic** [comment]
This is implemented. See [registration and discovery](http://textx.github.io/textX/stable/registration/)
