### ISSUE TITLE
Whitespace tokens are not processed

### ISSUE THREAD

**Issue by wryun** [textX/textX#188]
When skipws is False, if I create a whitespace token it seems to be skipped. For example

```
from textx.metamodel import metamodel_from_str

mm = metamodel_from_str('''
File: 'foo' ' ' 'bar';
''', skipws=False)
program = mm.model_from_str('foo bar')
```
The following error is thrown:
```
arpeggio.NoMatch: Expected 'bar' at position (1, 4) => 'foo* bar'.
```

However, it parses successfully if I instead replace `' '` with the equivalent `/(?i) /` (note that `/ /` does _not_ work, presumably because it simplifies to `' '`...).

**Comment by goto40** [comment]
I created a branch and added a testcase for it: bugfix/issue188

**Comment by goto40** [comment]
For me, this worked:
```
    mm = metamodel_from_str('''
        File[skipws]: 'foo' ' ' 'bar';
    ''')
    program = mm.model_from_str('foo bar')
```

**Comment by goto40** [comment]
After playing around: I encounter the same effect you observed with "noskipws":
```
def test_issue188_skipws_3():
    mm = metamodel_from_str('''
        File[noskipws]: 'foo' SPACE 'bar';
        SPACE[noskipws]: /\s/;                                # OK
    ''')
    program = mm.model_from_str('foo bar')

def test_issue188_skipws_4():
    mm = metamodel_from_str('''
        File[noskipws]: 'foo' SPACE 'bar';
        SPACE[noskipws]: ' ';                                 # NOT OK (unexpected)
    ''')
    program = mm.model_from_str('foo bar')
```

**Comment by goto40** [comment]
Intermediate result:
It seems that leading whitespaces are removed when building the grammar.
  * " x" --> "x" (space removed)
  * "x y" --> "x y" (ok)
  * " " --> "" (space removed)

**Comment by goto40** [comment]
@igordejanovic : Is it the case, that in lang.py we define strings as sequence of three parts,
 * ```'```
 * text
 * ```'```,
but, we do ignore whitespaces between these three parts?

If yes, do you see a simple solution to this (except the workaround sketched by @wryun to use a regepx without a plain whitespace)

See lang.py:
```
def str_match():            return [("'", _(r"((\\')|[^'])*"),"'"),\
                                    ('"', _(r'((\\")|[^"])*'),'"')]
```

**Comment by igordejanovic** [comment]
It was definitely a bug. Thanks @wryun for reporting and @goto40 for analysis and providing the tests.

It is fixed on branch `bugfix/issue188`. This change also provide a fix for another subtle error I didn't notice before.

@goto40 If everything is ok on your side this will be merged for v2 release that is about to happen :)

**Comment by goto40** [comment]
OK for me. Good work. Just merge the branch...

**Comment by goto40** [comment]
Note: I just saw single quote handling... Have I overseen double quote handling?

**Comment by wryun** [comment]
Thanks for the super fast response and fix!

**Comment by igordejanovic** [comment]
Merged to `master`
