### ISSUE TITLE
skipws at higher levels seems to affect skipping at lower levels in strange ways

### ISSUE THREAD

**Issue by wryun** [textX/textX#205]
For example, the following program returns '1', whereas I believe it should return '2' (i.e. it incorrectly matches the first choice in Word, rather than matching the first and the second).
```
from textx.metamodel import metamodel_from_str

mm = metamodel_from_str('''
SGroup[skipws]: '<s>' Sentence '</s>';
Sentence: /(?i) */ words*=Word /(?i) */;
Word: /(?i) */ ('bar' '.' | 'bar' | '.');
''', skipws=False, debug=True)

print(len(mm.model_from_str('''<s> bar . </s>''', debug=True).words))
```

If you remove skipws from SGroup, it returns 2. As far as I can see, this should have no effect on the parse in question.

**Comment by igordejanovic** [comment]
Initial discussion [at SO](https://stackoverflow.com/questions/57944531/how-do-you-correctly-mix-textx-skipws-non-skipws)

**Comment by igordejanovic** [comment]
@wryun Thanks for all reports.

**Comment by goto40** [comment]
Hmm. Good example. It seems that the ```skipws```-attribute is inherited by referenced rules. 

in your example ```SGroup``` has the ```skipws``` attribute. It calls the ```Sentence```, which has no specification concerning ```skipws```. Thus (obviously), ```Sentence``` inherits the ability. Same for the ```Word``` (called by the ```Sentence```). And here, 'bar' + SPACE + '.' are then **merged to one word** (skipping the whitespace).

The following illustrates the effect and demonstrates how to make the example work. Here, ```Sentence``` gets an explicit ```noskipws``` specifier to prevent the ability to be inherited...
```python
    mm = metamodel_from_str('''
        SGroup[skipws]: '<s>' Sentence '</s>';
        Sentence[noskipws]: /(?i) */ words*=Word /(?i) */;
        Word: /(?i) */ ('bar' '.' | 'bar' | '.');
    ''', skipws=False, debug=False)

    assert len(mm.model_from_str('''<s> bar . </s>''', debug=False).words) == 2
```

***Final question:*** Is this a feature or a bug? No idea...

**Comment by goto40** [comment]
If this is no bug, we need at least a docu update...

**Comment by goto40** [comment]
I created a possible bugfix branch with the different examples as unittests (one of them failing):
https://github.com/textX/textX/commit/2d1ef0f18d4050282dc60751bc888130435d4139

**Comment by igordejanovic** [comment]
`skipws/noskipws` carry its effect to the referenced rules. It is meant to be implemented that way. 
Thus, having these flags on a rule will effect all parses "passing over" the rule. If the docs is ambiguous on that part we shall fix the docs to be more explicit.
@wryun But, I think that the above example is not the same as the one posted on SO? I think that the original problem was an interplay of two rules with `skipws` and `noskipws`.

**Comment by goto40** [comment]
Thank you for the info. Indeed the behavior is implicitly defined in the example in http://textx.github.io/textX/stable/grammar/. I will correct the unittests (as example).

I will also have a look at the SO example...

**Comment by goto40** [comment]
The example reveals:

```python
    mm = metamodel_from_str('''
        Sentence[skipws]: words*=Word;
        Word[noskipws]: (ID '.') | ID | '.'; 
    ''')

    m = mm.model_from_str('''foo bar .''')
    assert "bar" == m.words[1]
```
fails with ```bar. != bar``` (```noskipws``` seems not work here.)

**Comment by goto40** [comment]
More experiments revealed:
```
    mm = metamodel_from_str('''
        Sentence[skipws]: words*=Word;
        Word[noskipws]: Helper | ID | '.';
        Helper[noskipws]: ID '.'; // OK
    ''')

    m = mm.model_from_str('''foo bar .''', debug=True)
    assert "foo" == m.words[0]
    assert "bar" == m.words[1]
```
is ok, but
```
    mm = metamodel_from_str('''
        Sentence[skipws]: words*=Word;
        Word[noskipws]: Helper | ID | '.';
        Helper: ID '.'; // noskipws seems not to be propagated....
    ''')
    assert "foo" == m.words[0]
    assert "bar" == m.words[1]
```
is not.

**Comment by igordejanovic** [comment]
I think I've found the source of the problem. It's `OrderedChoice` in Arpeggio. The `Word` node is `OrderedChoice` and it's not doing `skipws` set/restore as `Sequence` is doing. I'm preparing a fix in Arpeggio to cover this although `OrderedChoice` alone with `noskipws` is of little use in my opinion as you have to collect preceding spaces, as explained in SO thread, and that converts the rule to `Sequence` which behaves correctly.

**Comment by goto40** [comment]
@igordejanovic: Maybe you could have a look at https://github.com/textX/Arpeggio/pull/62.
With this I had some advances in this issue...

**Comment by goto40** [comment]
Oh sorry. I did not see you comment above. We had a similar analysis ;-)

**Comment by igordejanovic** [comment]
Ah, yes we did. :)

I just made a fix with test available on Arpeggio master branch so you can test.
It is still important to collect all whitespaces as explained at SO.

**Comment by goto40** [comment]
I still have problems (I think you need to define an explicit constructor in OrderedChoice).
```python
    def __init__(self, *elements, **kwargs):
        super(OrderedChoice, self).__init__(*elements, **kwargs)
```

**Comment by goto40** [comment]
(Strange, in your unittests you do not seem to need it)

**Comment by goto40** [comment]
Its not the constructor - I must have some issue in my tests...

**Comment by goto40** [comment]
OK. It works now.

It took me a while to get the point with the spaces I need to consume ("It is still important to collect all whitespaces as explained at SO"). I intuitively thought the "skipws=true" in the Sentence would do the job...

You may have a look at PR #209. Note sure if these examples are helping or confusing...

**Comment by goto40** [comment]
After I consumed the spaces before the word manually, it also worked with the old version of Arpeggio...

@wryun does it work for you? Or do you (or @igordejanovic) have a hint were the complicated cases are (compare my tests cases in #209, adapted from the examples I found here)?

**Comment by igordejanovic** [comment]
This is fixed in Arpeggio and we also have regression test in textX (#209

**Comment by wryun** [comment]
Sorry I haven't found time to have a look at this (and for the too cut down example!)

I still think the skipws/noskipws inheritance behaviour (good that it's fixed!) is a little problematic, because it means child rules without that specified can be interpreted in different ways depending on what their parent rule is (why would you want this? or am I misunderstanding something?).

**Comment by igordejanovic** [comment]
textX uses PEG and recursive descent with backtracking. So grammar is given and reason about as an imperative prescription for a parser what to do. Each rule could be thought as a sub-parser. It makes it natural that when you change the rule behavior it influences all input that is matched by that rule (and all that is referenced from that rule).

**Comment by wryun** [comment]
My problem with this is that each rule is _not_ an independent sub-parser, as far as I understand it. i.e. that if it has a different parent, it acts in a different way.

I'm also using textx so I don't have to bother writing a parser - this means that I'm trying to avoid understanding PEG :)

Ignoring what's intuitive, though, I would find it useful for the default behaviour of the entire parser to apply to all rules _unless_ overridden, rather than only the topmost rule (if it applies to only the topmost rule, what's the point of it? You could just define skipws/not on the topmost rule?).

**Comment by igordejanovic** [comment]
Well, you will hardly get away without understanding how underlying technology works :)

textX works (as all other PEG parser) in a say imperative way. Alternatives are ordered and that is distinctive feature of PEG which makes parsing unambiguous. So it is more like a computer program where you tell parser what to match first, what next and so on. Rule modifiers are implemented in such a way to change the parser state. So if your parser "runs over" some rule it will change its state until the parser returns from matching that rule.

You are right about parser level skipws, it could just be put on the top-level rule. The parser param is introduced before rule level modifiers and then rule level modifiers are introduced to enable more fine grained control.

Another important issue is the implementation. Some design decisions are driven by the naturalness and run-time performance of implementing something in PEG/recursive-descent parsing.
