### ISSUE TITLE
register_obj_processors not working as expected

### ISSUE THREAD

**Issue by mfrigerio17** [textX/textX#210]
Hi, I cannot get `register_obj_processors` to work with this simple example:

```Python
import textx as tx

grammar='''
Model:
    "Model" name=ID
    expr = Expr
;

Expr     : minus?="-"? arg= Value;
Value    : PILiteral | FLOAT;
PILiteral: /[P|p][I|i]/ ;
'''

modelstr='''
Model Foo
- PI
'''

mm = tx.metamodel_from_str(grammar)
mm.register_obj_processors( {'PILiteral': lambda x: print("Yeah")} )
model = mm.model_from_str(modelstr)
# Does not print 'yeah' even though it matches the PILiteral
```

The PILiteral rule is matched (a string different from 'PI' would result in an error), however the registered processor is not called.
Why is that?
Thank you

**Comment by mfrigerio17** [comment]
I can workaround it with
```Python
'''
Expr     : minus?="-"? arg= Value;
Value    : MyPI | FLOAT;
MyPI     : pi=PILiteral;
PILiteral: /[P|p][I|i]/ ;
'''
```
and then register a processor for `MyPI` instead, but the grammar is unnecessarily complicated.
In fact, at this point I would not even need a custom processor, as `MyPI`is not a match rule, and it results in an instance of type `MyPI`, not a string (my ultimate need is to distinguish the PIs in my model; if they are strings, I cannot do that)

**Comment by goto40** [comment]
Thank you for the report. I will have a look these days.

**Comment by goto40** [comment]
Hi. With textX 2.0.1 and python 3.7 I cannot reproduce the effect (I see the expected output).

Which versions do you use?

**Comment by mfrigerio17** [comment]
Python 3.5.2 and textX 1.8.0

Upgrading textX to 2.0.1 indeed solved the problem.
My apologies for not updating textX before posting...

Thank you

**Comment by goto40** [comment]
You are welcome.

Sometimes bugs in older versions reveal important inconsistencies. In this case it is not completely clear what happened. But we indeed worked on object processors between these releases, so I think we can ignore the effect for now....

Thank you.

**Comment by igordejanovic** [comment]
I can confirm that we did rework object processor call as in the old version it was impossible to attach object processor on "lower level" match rules, only top level match rules could have object processor. In this case `Value` is a top-level match rule as it is referenced from common rule while `PILiteral` is a "lower level" match rule as it is referenced only from `Value` i.e. other match rule.

In 2.x this behave as one would expect so object processors can be attached to any rule.
