### ISSUE TITLE
Project scaffolding

### ISSUE THREAD

**Issue by igordejanovic** [textX/textX#226]
I'm starting to work on a project scaffolding feature. The idea is to quickly generate language or generator project with proper `setup.py` and layout.

What I'm thinking at the moment is to make this feature just another generator which will take as an input a model in `Question & Answer` DSL (which will be built in) and generate the project. 
The input to the generator will be the info/answers produced by model interpretation (asking user question and getting answers).

This could be generalized to be able to produce an input to any generator by interpreting the input model.

Thus, the generator could be called using standard `generate` CLI command and a convenience command like `startproject` could be also added.

TODOs:
- [x] Implement questionnaire DSL (see https://github.com/textX/textx-lang-questionnaire)
- [x] Implement project generator from a specific questionnaire model (see https://github.com/textX/textX-dev/blob/master/textxdev/scaffold/__init__.py#L22)
- [x] Make a convenience shortcut CLI command (`startproject` instead of having to call `generate` with parameters). See https://github.com/textX/textX-dev/blob/master/textxdev/cli/startproject.py
- [x] document `startproject` command

**Comment by goto40** [comment]
Sounds great! I need to see maybe some details and to think more about it. 

 * I will definitively help to quickly build languages *and* generators.
 * I will help to build languages and generator in the way we think these have to be designed (e.g., file structure)
 * I will encourage to separate languages and generators. Modularity is a key maintenance aspect!

Note: I could imagine that some helper functions for generators could be useful as well... I always produce tons of clone code when creating multiple generators for one language (all the "overwrite"-flags, the "check-and-create-the-directories"-code, the "create/write the files"-code, etc.).  At the end I always trigger my clean "generate the text for that model"-function and do all the rest in a clone-code-cli-function...

**Comment by igordejanovic** [comment]
Fully agree on all points. Also, helper funcs is a great idea as they will reduce the boilerplate code in most common cases.

**Comment by danixeee** [comment]
I have [implemented project scaffolding](https://github.com/textX/textX-LS/pull/31/files) in _textX-LS_ extension, but didn't merge it to the master branch yet. Take a look if you can reuse some code/templates from there, although it doesn't support questionnaire.

**Comment by igordejanovic** [comment]
@danixeee  Will do. Thanks.
