### ISSUE TITLE
Infinite recursion in visualization

### ISSUE THREAD

**Issue by ari-koivula** [textX/textX#23]
When I try to visualize this model with `textx visualize simple.tx`:

```
List: members+=Value;
Value: ('{' List '}') | ID;
```

I get 

```
  ...
  File "c:\users\venti\documents\eclipse\textx\textx\export.py", line 48, in r
    result = "|".join([r(x) for x in s.nodes])
  File "c:\users\venti\documents\eclipse\textx\textx\export.py", line 50, in r
    result = " ".join([r(x) for x in s.nodes])
  File "c:\users\venti\documents\eclipse\textx\textx\export.py", line 46, in r
    result = text(s)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

`textx check simple.tx` says the meta-model is ok.

Also, this form works:

```
List: '{' members+=Value '}';
Value: List | ID;
```

but this one doesn't:

```
ListSyntax: '{' List '}';
List: members+=Value;
Value: ListSyntax | ID;
```

I think all of these should be should work. I tried with master branch of Arpeggio and textX, as well as Arpeggio-1.4 and textX-1.3.

**Comment by igordejanovic** [comment]
Thanks for the report. It looks like a bug in the dot export function.
I will look into it.

**Comment by ari-koivula** [comment]
There was a typo in the working example, it said `Value: ID;` instead of `Value: List | ID;`. I corrected it in the original message.

**Comment by igordejanovic** [comment]
Try `master` branch. Should be fine now.

**Comment by ari-koivula** [comment]
Yes it works. Thank you.
