### ISSUE TITLE
Non deterministic bug when parsing optional expression

### ISSUE THREAD

**Issue by wangluochao902** [textX/textX#241]
When a rule has optional expression, sometimes we can successfully parse a model, sometimes not. The following is a minimal example to duplicate.
```python
from textx import metamodel_from_str
from textx.exceptions import TextXSyntaxError
meta_s = '''
main_rule:
    "word1" (rule1 "word2" rule1)#
;

rule1:
    "word2"? "word3"?
;
'''
meta = metamodel_from_str(meta_s)

fail = 0
s = '''word1 word2 '''
for _ in range(100):
    try:
        model = meta.model_from_str(s)
    except TextXSyntaxError:
        fail += 1
print(fail)
```

Here is the error message when failing:
```
TextXSyntaxError: None:1:13: error: Expected 'word3' or 'word2' at position (1, 13) => 'rd1 word2 *'.
```

Note that the script only print out `0` or `100`. So the behavior is fix for each run.

textx version is `'2.1.0'`

**Comment by igordejanovic** [comment]
Hi, thanks for the report. This is a very interesting case.

The problem is usage of [unordered group](http://textx.github.io/textX/stable/about/comparison/#unordered-groups) `(rule1 "word2" rule1)#`. Unordered group will match its constituents in *any* order, thus by definition it is not deterministic. If all constituents match different things the order doesn't matter. The problem here is that all constituents can match "word2" which make it non-deterministic and dependent on which match will be tried first.

Well, that is the analysis but I'm not sure that this is a bug at all. To resolve this one would need to define the exact order how unordered group constituents should be matched which might be arbitrary in my view. What behavior did you expect for the unordered group? Maybe just a fix in the docs is needed to cover this case?

**Comment by wangluochao902** [comment]
you are right @igordejanovic . After I make it sequential, the error is deterministic. `fail` is`100` all the time. However, there should no error produced given `s = '''word1 word2'''` right?
```python
from textx import metamodel_from_str
from textx.exceptions import TextXSyntaxError

meta_s = '''
main_rule:
    "word1" rule1 "word2"
;

rule1:
    "word2"? "word3"?
;
'''

meta = metamodel_from_str(meta_s)

fail = 0
s = '''word1 word2'''
for _ in range(100):
    try:
        model = meta.model_from_str(s)
    except TextXSyntaxError:
        fail += 1
print(fail)
```
The error message is the same
```textx.exceptions.TextXSyntaxError: None:1:12: error: Expected 'word3' or 'word2' at position (1, 12) => 'ord1 word2*'.```

Since all expression in rule1 is optional, `s` should meet the `main_rule`. I am writing some script to automatically create rules. So I may end up with rules above. I expect `s` to be parsed successfully.

**Comment by wangluochao902** [comment]
By the way, the python `re` package has the correct behavior.
```python
>>> re.match(r'ab?c?b', 'ab')
<re.Match object; span=(0, 2), match='ab'>
```
I understand checking all possible cases before raising an error will slow down the process. But I think such mechanism is required.

**Comment by igordejanovic** [comment]
The underlying parser of textX is PEG and it is the way it operates (at least in my understanding which might be wrong). The backtracking is done on the sequence level. When `rule1` sequence succeed the parsing will continue and the backtracking will not try to make another combination of its optional matches. 

You are right, it would gone in the exponential time before reporting an error, not only in the worst case but always, every optional match would need to be checked. That would make parser unusable.

So, if you have sequence where its constituents could match the same you have to write your grammar in the proper way. The same is true e.g. when needing to order your alternative matches in the proper way (no ambiguity reporting in PEG).

In this case you would need something like:
```
main_rule:
    "word1" (rule1 "word2" | "word2")
;

rule1:
    "word2"? "word3"?
;
```
This is from the top of my head so might not describe the same language but you can get the idea.

**Comment by wangluochao902** [comment]
Thank you for the detailed explanation! I will try to avoid ambiguous ordering.

You mentioned unordered group is non-deterministic. Is it possible to make it deterministic? That will make it easier to avoid ambiguous ordering which will result in errors mentioned above.

**Comment by igordejanovic** [comment]
I guess it is possible and yeah, I agree that if possible it should be done so lets leave this issue open until that is resolved.

**Comment by igordejanovic** [comment]
@wangluochao902 The fix is available on the `master` Arpeggio branch. Please install Arpeggio from the master branch and test.

**Comment by wangluochao902** [comment]
It works now. Thanks
