### ISSUE TITLE
Can not match "\b" as word boundary in the a regex

### ISSUE THREAD

**Issue by wangluochao902** [textX/textX#259]
Here is a example to replicate the error:
```
from textx import metamodel_from_str
from textx.exceptions import TextXSyntaxError

meta_s = '''
main_rule:
    /[0-9]+\b/ "hi"
;

'''

meta = metamodel_from_str(meta_s)
s = '''2 hi'''

model = meta.model_from_str(s)
```

Here is the error message `textx.exceptions.TextXSyntaxError: None:1:1: error: Expected '[0-9]' at position (1, 1) => '*2 hi'.` Note that the expected `'[0-9]'` is different from the regex in the main_rule.

If I delete the "\b" in the regex, then it works perfectly.

**Comment by igordejanovic** [comment]
`\b` is interpreted by Python interpreter as backspace so the input grammar is changed. To prevent these problems always use raw string when specifying the grammar by putting `r` just before the grammar string:
```
meta_s = r'''
...
```

**Comment by wangluochao902** [comment]
Thanks. That works.
