### ISSUE TITLE
[Ext]RelativeName scope providers accept any referenced object that contains the lookup name in its name

### ISSUE THREAD

**Issue by mathias-luedtke** [textX/textX#267]
Example:

https://github.com/textX/textX/blob/719997751a1798f6ff9cf9256f07d13641525ae9/tests/functional/test_scoping/components_model1/example.components#L27 
 `output1`  can be changed to any substring (e.g., `o`, `out`, `pu`) and the tests still pass.

If multiple objects match the substring, the first (in parsing order or along the extension chain) will be returned.

This seems to be a regression of #186:

https://github.com/textX/textX/blob/719997751a1798f6ff9cf9256f07d13641525ae9/textx/scoping/providers.py#L593
https://github.com/textX/textX/blob/719997751a1798f6ff9cf9256f07d13641525ae9/textx/scoping/providers.py#L602

and

https://github.com/textX/textX/blob/719997751a1798f6ff9cf9256f07d13641525ae9/textx/scoping/providers.py#L661
https://github.com/textX/textX/blob/719997751a1798f6ff9cf9256f07d13641525ae9/textx/scoping/providers.py#L671

@goto40's docstring mentions this new behavior, but I doubt that these matches were intended:
https://github.com/textX/textX/blob/719997751a1798f6ff9cf9256f07d13641525ae9/textx/scoping/providers.py#L573

**Comment by goto40** [comment]
Thank you for the detailed bug report. There is definitely something wrong. Especially this substring logic look suspicious... (`x.name.find(name_part)`). We need some time to clarify this.

**Comment by goto40** [comment]
I think I understood (bug in `RelativeName` and `ExtRelativeName`) 
 * `get_reference_propositions` is intended to be used by some editor for auto completion. Here, we need the substring logic... (we want all objects which names contain the substring we pass). 
 * reference lookup (`__call__`) just delegates its functionality to `get_reference_propositions`.
 * However, I forgot to get rid of the substring logic. We want a perfect match in `__call__`. We could simply post process the list returned by `get_reference_propositions`.

I will see if I find time now. Give me time until end of August. However, you are welcome to contribute...

**Comment by mathias-luedtke** [comment]
> We could simply post process the list returned by get_reference_propositions.

That should be simple, I will try to patch it.
