### ISSUE TITLE
v2.2.0 breaks inheritance for user defined classes

### ISSUE THREAD

**Issue by fgro93** [textX/textX#270]
```
from textx.metamodel import metamodel_from_str

grammar = """
MyModel: 'model' name=ID
  connections+=Connection
  sender+=Sender
  receiver+=Receiver;


Sender: 
  'outgoing' name=ID 'over' connection=[Connection|ID];

Receiver: 
 'incoming' name=ID 'over' connection=[Connection|ID];

Connection: 
  'connection' name=ID
  'port' port=STRING 
  'ip' ip=STRING;
"""

modelstring = """
model Example
connection conn port "1" ip "127.0.0.1"

outgoing out0 over conn
incoming in0 over conn

"""
class ConnectionHandler(object):
    def _init_(self):
        print('')

    def awesomeMethod4SenderAndReceiver(self):
        print("I am really important for Sender and Receiver")

class Sender(ConnectionHandler):
    def _init_(self, name=None, port=None):
        print('')

class Receiver(ConnectionHandler):
    def _init_(self, name=None, port=None):
        print('')

mm = metamodel_from_str(grammar, classes=[ConnectionHandler, Sender, Receiver])
m = mm.model_from_str(modelstring)
```

This minimal example results in the following error:

```
Traceback (most recent call last):
  File "C:\Users\v040226\Workspaces\francaWorkspace\ErrorReproduce\src\main.py", line 47, in <module>
    m = mm.model_from_str(modelstring)
  File "C:\Program Files\Python38\lib\site-packages\textx\metamodel.py", line 584, in model_from_str
    model = self._parser_blueprint.clone().get_model_from_str(
  File "C:\Program Files\Python38\lib\site-packages\textx\model.py", line 282, in get_model_from_str
    model = parse_tree_to_objgraph(
  File "C:\Program Files\Python38\lib\site-packages\textx\model.py", line 680, in parse_tree_to_objgraph
    model = process_node(parse_tree)
  File "C:\Program Files\Python38\lib\site-packages\textx\model.py", line 498, in process_node
    process_node(n)
  File "C:\Program Files\Python38\lib\site-packages\textx\model.py", line 564, in process_node
    value = process_node(n)
  File "C:\Program Files\Python38\lib\site-packages\textx\model.py", line 483, in process_node
    parser.metamodel._init_obj_attrs(inst)
  File "C:\Program Files\Python38\lib\site-packages\textx\metamodel.py", line 452, in _init_obj_attrs
    for attr in obj.__class__._tx_attrs.values():
  File "C:\Program Files\Python38\lib\site-packages\textx\model.py", line 315, in _getattribute
    return super(user_class, obj).__getattribute__(name)
  File "C:\Program Files\Python38\lib\site-packages\textx\model.py", line 311, in _getattribute
    return user_class._tx_obj_attrs[id(obj)][name]
AttributeError: type object 'ConnectionHandler' has no attribute '_tx_obj_attrs'
```

We are currently not sure on how to fix this issue

**Comment by igordejanovic** [comment]
Thanks for the report. Would you be able to make a PR with failing regression test following the layout of other regression tests [here](https://github.com/textX/textX/tree/master/tests/functional/regressions).

**Comment by goto40** [comment]
Is `ConnectionHandler` part of your grammar as well ? In the example sketched above, the user class is not used in the Grammar?

**Comment by fgro93** [comment]
@goto40 as shown in the example, it is not.

With the https://github.com/fgro93/textx-pyecoregen we have inheritance with classes that are not part of the grammar.

@igordejanovic I don't think I have time to write tests. I'm sorry :(

**Comment by goto40** [comment]
Don't worry, we will try to reproduce it...

**Comment by goto40** [comment]
Analysis ongoing: https://github.com/textX/textX/pull/273

**Comment by goto40** [comment]
Why do you need a used defined class as base class which is not defined in the grammar? See pull request...

**Comment by fgro93** [comment]
Generating user classes from ECore meta-models: https://github.com/textX/textX/issues/115

With this we create a bunch of classes, we take all of them and use them as user defined classes. Some classes which are created are not part of the grammar, only of the ecore model. If we cannot use all classes, we have to manually create a list with all classes that are part of the grammar. 

It's more convenient and easier to maintain if we can use all of the created classes as user defined classes.

**Comment by igordejanovic** [comment]
Classes not found in the grammar and thus not instantiated by textX shouldn't be supplied in the list of classes in the `metamodel_from*` calls. Accepting other classes might open a window for hard to trace bugs. I suggest solving this issue by catching this error and trowing appropriate exception with the link to the docs where rationale is explained like we did for unhashable name recently.

**Comment by goto40** [comment]
Couldn't we somehow remove/ignore such classes automatically?

**Comment by igordejanovic** [comment]
We really should not do that as most of the time passing an unused class is an error and we should treat it as such. In my view the use-case reported here is very specific for pyecoregen and should be handled there.
Imagine a user mistakenly passing a wrong class (might be named similarly as the one he actually wanted) and then wonders why his class is not working.

An equivalent example in Python would be:
```python
params = {'a': 2, 'b': 3}
def f(a):
    print(a)

f(**params)
```

Python will complain about getting a parameter `b` which is not expected. This behavior in my view is right. If Python would ignore unused params it would really be very bad.

The only problem I see here is that the error reported should be better. But I would leave the check for unused classes in place. 

Of course, I'm open for discussion.

**Comment by goto40** [comment]
OK.

**Comment by goto40** [comment]
Note: I have not correctly documented where `_tx_obj_attrs` is set. Need to rework the comments...

**Comment by goto40** [comment]
Please have a look at the current master, if the fix works for you. You need to use the callback solution (see metamodel.md and/or the unit tests).

**Comment by igordejanovic** [comment]
I guess this is resolved. If not, please reopen.
