### ISSUE TITLE
Syntax error in generated dot file

### ISSUE THREAD

**Issue by hlouzada** [textX/textX#275]
The generated visualization dot file contains an syntax error if the character `<` or `>` is placed inside an HTML table within an label.

Steps to reproduce:
Run this exemple modified from https://textx.github.io/textX/stable/visualization/
```py
from textx import metamodel_from_str
from textx.export import metamodel_export


grammar = '''

Comment:
    "<:" ( !"*/" /./ )* ":>"
;

EntityModel:
  entities+=Entity    // each model has one or more entities
;

Entity:
  'entity' name=ID '{'
    attributes+=Attribute     // each entity has one or more attributes
  '}'
;

Attribute:
  name=ID ':' type=[Entity]   // type is a reference to an entity. There are
                              // built-in entities registered on the meta-model
                              // for primitive types (integer, string)
;
'''

entity_mm = metamodel_from_str(grammar)

metamodel_export(entity_mm, 'entity_model.dot')
```
Now execute:
```
$ dot -Tpng -O entity_model.dot
```

When parsed _graphviz_ will return an syntax error and that will be solved only if all `>` and `<` are removed. An possible solution is to replace them with their respective Unicode character as `&#62;` and `&#60;` respectively.

OS: Ubuntu 20.04 LTS
Python: Python 3.8.5
textX: 2.2.0

**Comment by igordejanovic** [comment]
@hlouzada Thanks for the detailed report.

**Comment by goto40** [comment]
@hlouzada : the bug should be fixed. You can have a look at the current master.

**Comment by hlouzada** [comment]
Thanks for the fix. It's working now.
