### ISSUE TITLE
Relax dependency to the click library

### ISSUE THREAD

**Issue by igordejanovic** [textX/textX#286]
Since `click` is used only for CLI operations it can be moved to `extras_require` section to relax further dependencies for non-dev installations.

**Comment by goto40** [comment]
But we need click for non dev installs? What das 'extra' mean?

**Comment by goto40** [comment]
I had issues with py.test runner being required by arpeggio for non dev installs.

**Comment by goto40** [comment]
Good idea to reduce dependencies!

**Comment by igordejanovic** [comment]
`extras_require` are optional deps used for some of the features. Here we need it only for CLI so if we want to use `textx` cli command we would install with:
```
pip install textX[cli]
```
This will make textX easier to deploy as the only dependency would be Arpeggio. 

Furthermore, if cli deps are not installed trying to run `textx` should provide some helpful message that gives instruction to `pip install textX[cli]` in order to use it.

What kind of problem did you have with Arpeggio?

**Comment by goto40** [comment]
For arpeggio I had to tweak the following line to install it on an offline system: `setup_requires=['pytest-runner']`
