### ISSUE TITLE
Possible RREL Extension

### ISSUE THREAD

**Issue by goto40** [textX/textX#303]
While RREL is very elegant to specify many scoping issues, the "way through the model" while traversing the RREL path is lost.

Example:
```
        Model:
            structs+=Struct
            instances+=Instance
            references+=Reference;
        Struct:
            'struct' name=ID '{' vals+=Val '}';
        Val:
            'val' name=ID (':' type=[Struct])?;
        Instance:
            'instance' name=ID (':' type=[Struct])?;
        Reference:
            'reference' ref=[Val|FQN|instances.~type.vals.(~type.vals)*];
        FQN: ID ('.' ID)*;
```
A Reference `reference d.c.b.a.x` thus defines a way through the model - but only the
destination `x` is stored as result.

I would like to be able to access also the path tough the model: all elements `d`, `c`, `b`, `a`, `x`.

It is no big problem to store the way through the model while resolving a reference with RREL, I am unsure how to pass the result (the path `d`, `c`, `b`, `a`, `x`) to the model...

Any idea?

**Comment by igordejanovic** [comment]
Could you elaborate on the use-case?

**Comment by goto40** [comment]
> Could you elaborate on the use-case?

See #304 
I hope I could explain it there...

**Comment by igordejanovic** [comment]
As you suggested, we might introduce `_tx_` variable, e.g. `_tx_<ref_name>` to hold the path. This feature might be controlled using metamodel constructor param.

Another idea: how about extending RREL to resolve to a path instead to a target object? E.g. `+p` (like `+m` we have now) would mean that the reference will be a list of element found along the path. The last object in the list will be the target object. Is there any issue we could have with this approach? It might be better as we could have a per-reference control.

**Comment by goto40** [comment]
Let's wait a few days and think about it...

**Comment by goto40** [comment]
I picked up your suggestion and added a wrapper (`ReferenceProxy`) around it to support our type semantics. Please look at #304
