### ISSUE TITLE
Can't use cli tool

### ISSUE THREAD

**Issue by jonathan-dev** [textX/textX#309]
The `textx` command fails with this error message:
```
raise Exception('textX must be installed with CLI dependencies to use '
Exception: textX must be installed with CLI dependencies to use textx command.
pip install textX[cli]
```
and pip can't find any matches for `textX[cli]`
What's wrong here?

**Comment by igordejanovic** [comment]
I can't reproduce the problem. It might be a transient problem with PyPI. Do you still have this issue?

Another source of problem might be if you are using zsh or some other shell that interprets `[]` specially. 
If that is the case try to escape brackets like this  `pip install textX\[cli\]`

**Comment by jonathan-dev** [comment]
It seems that zsh caused the problem for me. Thanks a lot I wasn't aware of the special interpretation of `[]` .
