### ISSUE TITLE
Edit Books

### ISSUE THREAD

**Issue by m-laniakea** [TextX/TextX#31]

**Comment by aarongup** [comment]
what do you mean..?

**Comment by m-laniakea** [comment]
Instead of deleting and re-adding the book, users can just edit the book details.

**Comment by aarongup** [comment]
in edit branch. mostly done. Just need to do error checking

**Comment by aarongup** [comment]
did many error checks
- 13 digit isbn
- negative price
- invalid price
- negative cond
- invalid cond

**Comment by aarongup** [comment]
Done without forms.

**Comment by m-laniakea** [comment]
Two things still need fixing: 
- Logins on the book details page
- Remove the aggressive "forbidden" symbol when hovering

**Comment by aarongup** [comment]
Fixed beside one issue, how to redirect back to edit book page upon entering invalid data?

**Comment by aarongup** [comment]
fixed :+1:
