### ISSUE TITLE
Assertion error when calling object processors on model modified by custom classes

### ISSUE THREAD

**Issue by igordejanovic** [textX/textX#310]
I've stumbled upon an exception in a situation when the model is reduced by custom classes (something often done in expression processing for simplification and optimization).

https://github.com/textX/textX/blob/5ebe500eb647fdf7ec6fab4ac27beae24bf25678/textx/model.py#L767-L773

This `assert` here ensures that grammar rule is abstract, which is correct if the model is unmodified, but generally to enable reduction this should be relaxed.

The fix would be simply to remove the assert. I'm working on a test case that manifests the problem.

**Comment by goto40** [comment]
Hm. Seems OK to me... Not 100% sure.

The reduction cannot happen later?

**Comment by igordejanovic** [comment]
Yeah, it could but IMHO the implementation would be less elegant. On the other hand, should we prohibit modifications in user classes? I don't think we did that so far, the same as we allow modifications in object processors.  Conceptually, by allowing custom classes in the first place we already agreed to model modifications. I guess the meta-model creator should take care of what they are doing. Not sure 100% either it is a good direction. Will post a PR shortly so we can discuss there.
