### ISSUE TITLE
problem with resolution of links with complex names

### ISSUE THREAD

**Issue by brain-HUN** [textX/textX#32]
Hi,

During development I have run into a strange problem. I am not sure whether this is a bug or it's intentional. If I try to reference to an object that has name more complex than a simple ID I get an error. 
I have created a minimal example to demonstrate the problem :

    from textx.metamodel import metamodel_from_str
    tx= """
    EntityModel:
      Entity
      Reference
    ;
    EntityName:
      ID '.' ID
    ;
    Entity:
      'entity' name=EntityName 
    ;
    Reference:
      'reference' ref=[Entity]
    ;
    """
    text= """
    entity Some.Person
    reference Some.Person
    """
    mm= metamodel_from_str(tx)
    model= mm.model_from_str(text)

Running the above program gives the following error:
Expected EOF at position (3, 15) => 'rence Some*.Person

Somehow when referencing the program doesn't use original expression for name, but rather expects an ID.

**Comment by igordejanovic** [comment]
Hi,
Reference resolving is done using `ID` rule by default. To change the default try this:
```
Reference:
  'reference' ref=[Entity|EntityName]
;
```
This syntax in reference definition enables you to define arbitrary Match rule to be used as a reference name.
This is covered in the docs [here](http://www.igordejanovic.net/textX/grammar/#references).

**Comment by brain-HUN** [comment]
Thank you that helped the example to run, but it looks like I have oversimplified the example a little. Changing the grammar slightly:

    tx= """
    EntityModel:
      entity=Entity
      reference=Reference
    ;
    EntityName:
      first=ID '.' second=ID
    ;
    Entity:
      'entity' name=EntityName 
    ;
    Reference:
      'reference' ref=[Entity]
    ;
    """

With this grammar  I get the following error:
Unknown object "<textx:EntityName object at 0x24936844a58>" of class "Entity" at (3, 11)

Which is probably caused by the fact that the name will be an object not a string. Is there a way around this? Like giving a custom class as EntityName with a __eq__ operator?

Thanks

**Comment by igordejanovic** [comment]
Automatic reference resolving is supported for string names only.
For your language you could either
- use Match rule for `EntityName` and register object post-processor for splitting the name and providing first and second part as additional attributes on `Entity` (see  [object processors](http://www.igordejanovic.net/textX/metamodel/#object-processors) in the docs),
- Register your own `Entity` Python class and provide Python properties for accessing first and second part of the name (see [metamodel/custom classes](http://www.igordejanovic.net/textX/metamodel/#custom-classes) in the docs),
- Implement your own reference resolution based on the complex ref/name/object matching you need. In this case you would match reference as `ref=MyEntityName` where `MyEntityName` is match rule for FQN. Register model processor that will search the model for all references and replace the strings with a proper object references (first you will need to collect all name/targetobj pairs).

**Comment by brain-HUN** [comment]
Thank you for the answer. As there is no quick way around the issue I'll consider my options
