### ISSUE TITLE
[Link rule reference] example error

### ISSUE THREAD

**Issue by Xziguoux** [textX/textX#321]
i have a try with the [Link rule reference] example:
# lk_ref.tx
```
ScreenType:
  'screen' name=ID "{"
  '}'
;

ScreenInstance:
  'screen' type=[ScreenType]
;
```
# lk.hello
```
// This is a definition of the ScreenType object
screen Introduction {

}

// And this is a reference link to the ScreenType object defined above
// ScreenInstance instance
screen Introduction
```
then i have a check with the command
```
textx check lk.hello --grammar lk_ref.tx
Error: None:5:1: error: Expected EOF at position lk.hello:(5, 1) => 'ion {  }  *screen Int'
```

what is wrong ???

**Comment by igordejanovic** [comment]
The snippet is not complete. It just shows usage of link rule reference in a larger grammar.

For a complete stuff see [examples](https://github.com/textX/textX/tree/master/examples) or `tutorials` section of the docs. For example [robot tutorial](http://textx.github.io/textX/latest/tutorials/robot/) or for a link rule reference [entity tutorial](http://textx.github.io/textX/latest/tutorials/entity/).

**Comment by Xziguoux** [comment]
thanks very much  for your quick response
