### ISSUE TITLE
Cannot mix references and types in ordered choice rule

### ISSUE THREAD

**Issue by tha23rd** [textX/textX#322]
Hi, we are trying to create a rule that matches on either a type or a reference to an object of a different type, shown as follows:

`('assert' pred=PredicateModel) | ('assert' pred=[StateModel])`

```
StateModel:
    'state' name=ID ('when' when=[StateModel])?':'
        asserts*=AssertModel
        states*=StateModel
    ';'
;
AssertModel:
    ('assert' pred=PredicateModel) | ('assert' pred=[StateModel])
;

PredicateModel:
    left=SQLLike op=Operator right=SQLLike
;
Operator:
    '>' | '=' | 'not' | 'in'
;
SQLLike:
    BaseType | "null" | ID | List
;
BaseType:
    INT|FLOAT|STRING|BOOL
;
```

Implemented as language:
```
state mystate:
    assert 4 > 4

state anotherstate:
    assert mystate
```

Essentially, we'd like to parse either the instantiation of `PredicateModel` OR a reference to an already created `StateModel`.

The above grammar causes the following error:
Unknown object "<textx:PredicateModel instance at 0x10eeead60>" of class "OBJECT"

Are we using the wrong syntax here, is this not allowed by textx, or am I just completely missing something?

Thanks!

**Comment by goto40** [comment]
A simple solution could be to define a separate "keyword" for both caees:
E.g.
 * `assert 4>4`
 * `assert_state mystate`
In your case, the first `assert` case is chosen (triggered by the keyword `assert`) and a `PredicateModel` is expected...

**Comment by tha23rd** [comment]
hi @goto40, thanks for the workaround!

is this the only possible solution? while it works, I think we would like to have a unified keyword if possible.

**Comment by goto40** [comment]
I you prefer you can introduce a separate keyword (e.g. `&`) to separate both cases:
```
state mystate:
    assert 4 > 4

state anotherstate:
    assert &mystate
```
I had to modify the model in some parts, since it seemed incomplete (e.g. `List` was missing and the `;`):
```
import textx

grammar = '''
StateModel:
    'state' name=ID ('when' when=[StateModel])?':'
        asserts*=AssertModel
        states*=StateModel
    //';'
;
AssertModel:
    'assert' (pred_mod=PredicateModel | '&' pred_ref=[StateModel])
;                                       ^^^ KEYWORD TO 'SELECT' REF-CASE
//            ^^^^^^^^^ SEPARATE MEMBER TO DISTINGUISH BOTH CASES...

PredicateModel:
    left=SQLLike op=Operator right=SQLLike
;
Operator:
    '>' | '=' | 'not' | 'in'
;
SQLLike:
    BaseType | "null" | ID // | List
;
BaseType:
    INT|FLOAT|STRING|BOOL
;
'''

model = '''
state mystate:
    assert 4 > 4

state anotherstate:
    assert &mystate
'''

mm = textx.metamodel_from_str(grammar)
m = mm.model_from_str(model)

for s in textx.get_children_of_type('StateModel', m):
    print(f"stateModel: {s.name}")
```

In any case you need to give the parser a hint, which branch to choose....

**Comment by tha23rd** [comment]
@goto40 my bad, copy and pasting some scratch code

thank you so much for that example! I think that could work for us. Going to go ahead and mark this issue as resolved, thanks for your time.

**Comment by goto40** [comment]
More infos:
 * http://textx.github.io/textX/stable/grammar/#ordered-choice
 * http://textx.github.io/textX/stable/about/comparison/#comparing-textx-to-other-tools
