### ISSUE TITLE
Difference in behavior when reading grammar from string or from file 

### ISSUE THREAD

**Issue by stanislaw** [textX/textX#323]
Hello,

Thanks again for creating textX. This time it seems to be working well for a definition of a ASN.1 parser :smile: 

There is one issue that I have been hitting with my colleague and I apologize if we missed something trivial in the documentation. 
The issue manifested itself in several ways that we could not make sense of. After some reduction, we could find the difference in how the parser behaves differently when parsing the same grammar from a file or from a string.

In the example below, we would expect the code to produce something like this:

```
<textx:Asn1 instance at 0x....>  # parsing from a string
<textx:Asn1 instance at 0x....>  # parsing from a file
```

Instead, only the parsing from string works and parsing from a file results in the exception.

---

**grammar.tx**

```py
Asn1[noskipws]:
  'Module-' module_name='Foo' ' DEFINITIONS AUTOMATIC TAGS ::= BEGIN' (comment=AsnComment)? '\n'
  'END'
;

AsnComment[noskipws]:
  ' -- ' (comment=/[a-z ]+$/)
;
```

**main.py**

```py
from textx import metamodel_from_str, metamodel_from_file

string_metamodel = metamodel_from_str('''
Asn1[noskipws]:
  'Module-' module_name='Foo' ' DEFINITIONS AUTOMATIC TAGS ::= BEGIN' (comment=AsnComment)? '\n'
  'END'
;

AsnComment[noskipws]:
  ' -- ' (comment=/[a-z ]+$/)
;
''')


textx_input = '''
Module-Foo DEFINITIONS AUTOMATIC TAGS ::= BEGIN -- test comment
END
'''.lstrip()


model = string_metamodel.model_from_str(textx_input, debug=False)
print(model)

file_metamodel = metamodel_from_file(
    "grammar.tx",
    # classes=cls.used_classes,
)
model = file_metamodel.model_from_str(textx_input, debug=False)
print(model)
```

**The output:**

```
/home/stanislaw/.pyenv/versions/3.6.2/bin/python /home/stanislaw/PycharmProjects/textx_playground/main.py
<textx:Asn1 instance at 0x7f32ddc4b0b8>
Traceback (most recent call last):
  File "/home/stanislaw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/textx/model.py", line 291, in _parse
    return self.parser_model.parse(self)
  File "/home/stanislaw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/arpeggio/__init__.py", line 291, in parse
    result = self._parse(parser)
  File "/home/stanislaw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/arpeggio/__init__.py", line 370, in _parse
    result = e.parse(parser)
  File "/home/stanislaw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/arpeggio/__init__.py", line 291, in parse
    result = self._parse(parser)
  File "/home/stanislaw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/arpeggio/__init__.py", line 370, in _parse
    result = e.parse(parser)
  File "/home/stanislaw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/arpeggio/__init__.py", line 789, in parse
    result = self._parse(parser)
  File "/home/stanislaw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/arpeggio/__init__.py", line 898, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "/home/stanislaw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/arpeggio/__init__.py", line 1718, in _nm_raise
    raise self.nm
arpeggio.NoMatch: Expected '\n' at position (1, 64) => 'st comment* END '.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stanislaw/PycharmProjects/textx_playground/main.py", line 28, in <module>
    model = file_metamodel.model_from_str(textx_input, debug=False)
  File "/home/stanislaw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/textx/metamodel.py", line 617, in model_from_str
    pre_ref_resolution_callback=kwargs_callback)
  File "/home/stanislaw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/textx/model.py", line 332, in get_model_from_str
    self.parse(model_str, file_name=file_name)
  File "/home/stanislaw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/arpeggio/__init__.py", line 1516, in parse
    self.parse_tree = self._parse()
  File "/home/stanislaw/.pyenv/versions/3.6.2/lib/python3.6/site-packages/textx/model.py", line 297, in _parse
    expected_rules=e.rules)
textx.exceptions.TextXSyntaxError: None:1:64: error: Expected '\n' at position (1, 64) => 'st comment* END '.

Process finished with exit code 1
```

**Comment by goto40** [comment]
Try to use a raw multi-line string (put an "r" in front of the string, else `\n` is interpreted):
```
string_metamodel = metamodel_from_str(r'''
```
If it does not work, I can have a closer look...

**Comment by stanislaw** [comment]
You are right, I realized this difference on a way home already :smile: 

Actually, with the `noskipws` added, the behavior of `\n` that we have when reading from a non-raw multi-line string exactly corresponds to "this is a newline" semantics.

I think we are going to switch to reading the grammar from a Python constant but just out of curiosity: how should we indicate that we want a newline in the `.tx` file?

**Comment by igordejanovic** [comment]
It seems that backslash special chars (e.g. `\n`) are only supported in regex match, not string match. So `/\n/` should work. This should either be supported in string match also or documented.

**Comment by igordejanovic** [comment]
I did a little bit of investigation and I can confirm that backslash chars are not interpreted in string matches. I suggest we treat this as a bug as it is more intuitive for string matches to behave similarly to Python strings. The fix should be straightforward but it will introduce backward incompatibility for grammars that use unescaped backslashes in string matches.

**Comment by stanislaw** [comment]
On our side, we have switched to using Python strings because they scale better anyway - one can interpolate extra content into a Python string which makes the textX grammar a bit more "programmable". Currently, I see no use case for .tx files except for very basic intro-level grammars.

I could think of textX's documentation explaining this difference somewhere in the very beginning of the documentation but the documentation should be very clear because I could also see a hypothetical myself or my colleagues to easily miss the information about the difference in behaviour of the backslash characters.

**Comment by igordejanovic** [comment]
Actually, grammars from strings and files behave the same. The problem is that non-raw strings are processed by escaping from Python side, so textX gets already escaped grammar. There are several problems with this:
1. All backslashes are escaped, even in regexes which is not what we want (you will have to use double backslashes in regexes). So generally, raw strings should be used as @goto40 suggested, as what you see is what textX gets. But, if raw strings are used there is no way to specify special chars in string matches.
2. Apparent difference is non-intuitive (at least for me). Furthermore, there is no way to specify special chars in .tx grammars str matches.

I already did a fix locally. I haven't done thorough testing yet. Will do it in the next days.
The fix interprets backslash escaped chars in str matches as Python would. So both raw strings and .tx files should behave the same.

On the .tx note, I can see that your use case requires a dynamic creation of grammar but there are a lot of grammars that are static and kept in .tx files. Some of the benefits of using .tx files are using editor plugins for syntax highlighting and using textx CLI command for checking and visualization.

My point of view currently is that leaving it as is now and just documenting it can be hardly justified. Or to put it in the *Zen of Python* perspective *Special cases aren't special enough to break the rules* :)

**Comment by stanislaw** [comment]
> Actually, grammars from strings and files behave the same. The problem is that non-raw strings are processed by escaping from Python side, so textX gets already escaped grammar. There are several problems with this:
> 
> 1. All backslashes are escaped, even in regexes which is not what we want (you will have to use double backslashes in regexes). So generally, raw strings should be used as @goto40 suggested, as what you see is what textX gets. But, if raw strings are used there is no way to specify special chars in string matches.
> 2. Apparent difference is non-intuitive (at least for me). Furthermore, there is no way to specify special chars in .tx grammars str matches.

Was not intuitive to me either.
 
> I already did a fix locally. I haven't done thorough testing yet. Will do it in the next days. The fix interprets backslash escaped chars in str matches as Python would. So both raw strings and .tx files should behave the same.
> 
> On the .tx note, I can see that your use case requires a dynamic creation of grammar but there are a lot of grammars that are static and kept in .tx files. Some of the benefits of using .tx files are using editor plugins for syntax highlighting and using textx CLI command for checking and visualization.

Makes sense!

> My point of view currently is that leaving it as is now and just documenting it can be hardly justified. Or to put it in the _Zen of Python_ perspective _Special cases aren't special enough to break the rules_ :)

I am happy that this issue is producing a useful work increment 👍 
(even though we have solved it on our side by switching to a Python constant)

**Comment by igordejanovic** [comment]
> I am happy that this issue is producing a useful work increment +1
> (even though we have solved it on our side by switching to a Python constant)

Yup, seems like an important improvement. Thanks for bringing this up!

**Comment by igordejanovic** [comment]
Just in case someone lands into this thread. The nice explanation of the problem of backslash escaping and python raw strings can be found [here](https://docs.python.org/3/howto/regex.html#the-backslash-plague).
