### ISSUE TITLE
Grammar problem

### ISSUE THREAD

**Issue by francoisihry** [textX/textX#33]
Hi Igor Dejanović, I first want to congrat you for your work. textX is a realy easy and usefull DSL tool.
I am currently facing a problem in my grammar.
```
Method:
    'func('  (params+=Parameter[','])?  ')'
;

Parameter:
    (type=ID)?
    name=ID
;
```
And here is a simple test:
```
from os.path import join, dirname
from textx.metamodel import metamodel_from_file

def test():
    meta_model = metamodel_from_file(
        join(dirname(__file__), 'my_grammar.tx'))
    model = meta_model.model_from_str(
        """
        func( a b, c )
        """
    )
```
I get a syntax error : "Expected ID at position (2, 22) => 'c( a b, c *)"
So textX has recognized 'c' as a type instead of a name and expects to find a name next. I tried many other kind of pattern but I still get that error...
Any idea ?

**Comment by igordejanovic** [comment]
Hi François,
At first I thought that the solution would be simply:

```
Parameter:
    type=ID name=ID  |  name=ID
;
```

But currently that doesn't work as expected so it is a bug. Please leave this
issue open until fixed.

Until the issue is resolved you can use the following solution:

```
Method:
    'func('  (params+=Parameter[','])?  ')'
;
Parameter:
    ParameterWithType | ParameterWithoutType
;
ParameterWithType: type=ID name=ID;
ParameterWithoutType: name=ID;
```

**Comment by igordejanovic** [comment]
This issue is fixed. With the development version of textX the solution would be:

```
Method:
        'func('  (params+=Parameter[','])?  ')'
;
Parameter:
        type=ID name=ID  |  name=ID
;
```

Please see [the test for this issue](https://github.com/igordejanovic/textX/blob/master/tests/functional/regressions/test_issue33.py).

**Comment by francoisihry** [comment]
Great !
