### ISSUE TITLE
unordered group question

### ISSUE THREAD

**Issue by goto40** [textX/textX#358]
According to http://textx.github.io/textX/stable/grammar/#repetitions an unordered group must be applied to a sequence.

However, in https://github.com/textX/textX/blob/master/examples/pyFlies/pyflies.tx#L168 it is applied to an ordered choice.

Maybe we should clarify this in the docs...? Or did I misunderstood something?

Once we clarify this (how it should be) I can make a proposition for the docs. I could also elaborate on how optionals are handled in unordered groups...

**Comment by igordejanovic** [comment]
You are right. It wasn't clear enough. Actually, usage of ordered groups looks like an accidental feature :)
I did some more testing and addition to the docs to clarify. Will issue a PR shortly.

**Comment by igordejanovic** [comment]
Closed via #359
