### ISSUE TITLE
Parsing of floats ending with period.

### ISSUE THREAD

**Issue by jhrmnn** [textX/textX#37]
`FLOAT` seems to parse both `2.0` and `2`, but not `2.`, is this intended behavior?

**Comment by igordejanovic** [comment]
I don't think so. I'll look into it.
In the meantime you can [create your own float type](http://www.igordejanovic.net/textX/metamodel/#match-filters).

**Comment by jhrmnn** [comment]
I already did. The documentation is superb.

**Comment by borismarin** [comment]
See https://github.com/igordejanovic/textX/pull/47.
