### ISSUE TITLE
Problem with relative rrel path evaluation in case of multiple model files

### ISSUE THREAD

**Issue by goto40** [textX/textX#377]
### Problem

In case of multiple files the docu says:
"Then, in case of no match, other loaded models are searched."
("+m" in rrel expressions, see https://textx.github.io/textX/3.0/rrel/#rrel-and-multi-files-model).

The **current implementation** is done in the following way
 * evaluate RREL starting from current model element
 * if ok: return result
 * else: try all included models and evaluate RREL starting from ***the root of the included model***

This is ok for most use cases (especially those where we have a RREL starting with "`^`"). Here, starting from the root of all included models is what is expected...

This is not ok if we have a ***relative RREL path*** and we want to switch model files ***within the RREL path***.

I suggest that instead of current implementation: (**suggested new implementation**)
 * evaluate RREL starting from current model element
    * ***when reaching the root of the model use all imported models for the search*** (**impact**: this affects in particular the `class RRELNavigation` in `rrel.py`.
 * if ok: return result

### Example
(failing test for this grammar: https://github.com/textX/textX/blob/bugfix/rrel_lookup_multifile_problem/tests/functional/test_scoping/rrel_multifile/Grammar.tx)

          Model: includes*=Include a*=A r*=R;
          A: 'A' name=ID '{' ( a=A | p1=P1 )* '}'; 
          R: 'R' a+=[A|FQN|+pm:a*][','];
          P1: 'P1' a+=[A|FQN|+pm:..(..)*.a*][',']; // many times ".." and 1x "A"
          FQN: ID ('.' ID)*;
          Include: '#include' importURI=STRING;
          Comment: /\/\/.*?$/;

Here, we have a rule `P1` referencing `A` elements in some `a` attribute. It is mandatory not to search the `a` attribute within `P1`. With this, we need a mandatory "step back" with a `..` at the beginning of the RREL.
  * With the **current implementation**, when requiring some model data from other files, we fail to find the element locally and restart the search at the model root of other model files, and there want to go a "step back". This is not possible (because the model has no parent). --> The search fails - and this is not the expected behavior. 
  * With the **proposed new implementation**, we just switch model files when reaching the root of our model and everything works.

### Implementation and Test
 * Implementation:
    * add new logic (see above) in class `RRELNavigation`
    * update logic (check!) in `RRELDots`, `RRELZeroOrMore` (possible inspiration: see https://github.com/goto40/textx-cpp/blob/master/src/textx/rrel.cpp and corresponding unittests).
    * check all usages of `start_locally` and `start_at_root` with new impl.
 * Test: no impact on any other existing use case is expected (other unittest must work as expected). - New test as suggested in the branch above.

**Comment by igordejanovic** [comment]
@goto40  Good catch! The explanation sounds good. I'm only wondering about `we just switch model files when reaching the root of our model`. I suppose that we continue search with the remaining unconsumed part of the RREL and FQN. Do we repeat search through all models with the same remaining parts of RREL and FQN? I guess we should but just checking if I correctly understood your solution.

**Comment by goto40** [comment]
The basic idea is that the root of the models are handled as being merged:
In the navigation node you iterate over all attributes of all imported models, instead of iterating over the attributes from your own model only. There is no other special handling (maybe we missed special cases?). 

See https://github.com/goto40/textx-cpp/blob/1d8ea2802c99e0ec145f843e7fe1c23e3cc076d1/src/textx/rrel.cpp#L312
Here we have a `start` node. In case of processing the root of the model (no parent), the `start` is a list of all imported models. 

With this, you can extract a part of a model in a separate file, include the file and get the same scoping behavior.

Your question: if I understood correctly, you described what I mean. We just continue the search when swirching models without any special handling (especially no "restart" of the rrel search). 

What do you think...?

**Comment by goto40** [comment]
> Do we repeat search through all models with the same remaining parts of RREL and FQN? 

Yes.

**Comment by igordejanovic** [comment]
Sounds good! I only wonder do we need `+m` prefix at all since what you proposed sounds as the only logical behavior and I don't see any reason to limit search to only the current model if multiple models are loaded.

**Comment by goto40** [comment]
You are right. But this is a BIC (if we remove the `+m` from the grammar) .

**Comment by goto40** [comment]
For me it is ok

**Comment by igordejanovic** [comment]
Yup, you are right. We could leave it in the grammar for backward compatibility but anyway, searching through all the models when `+m` is not specified is still BIC. I suggest that we remove it in 4.0.

**Comment by goto40** [comment]
OK. I will make proposal / implementation

**Comment by goto40** [comment]
We should think of making the "importURI" feature (loading models) the default, independent of the scope providers (see `ModelLoader`). Let's discuss this in a separate issue... For this we need to recap how exactly it is now, how it could be, and what we think is the best... 

I added a note in `model.py`...

**Comment by igordejanovic** [comment]
> We should think of making the "importURI" feature (loading models) the default, independent of the scope providers (see ModelLoader).

I agree. Let's discuss that in a separate issue.
