### ISSUE TITLE
Can't  create rule with \ character

### ISSUE THREAD

**Issue by pvmm** [textX/textX#381]
I found a language that uses `\` as integer division, but I can't use that character in my rules. There isn't a way to create a regex with the `\` character when not using it to quote. When I use the `'\'` string like this:
```
IdvOp:              op1=MulOp ( opr='\'       op2=MulOp )*;
```
it turns `opr` into an empty string in the model. So `Print 1 2` (without the operator) works when it shouldn't. On the other hand
```
IdvOp:              op1=MulOp ( opr='\\'       op2=MulOp )*;
```
```
IdvOp:              op1=MulOp ( opr=/\/       op2=MulOp )*;
```
```
IdvOp:              op1=MulOp ( opr=/\\/       op2=MulOp )*;
```
```
IdvOp:              op1=MulOp ( opr=/\\\\/       op2=MulOp )*;
```
are all invalid and break the grammar with `TextXSyntaxError`.

**Comment by igordejanovic** [comment]
Be sure to use raw strings if you use grammar embedded in the Python code.

This is what I just tested to work:

```python
from textx import metamodel_from_str

grammar = r'''
Op: left=ID op='\'  right=ID;
'''

mm = metamodel_from_str(grammar)

model = mm.model_from_str(r'a \ b')

assert (model.left == 'a'
        and model.right == 'b'
        and model.op == '\\'
        and len(model.op) == 1)
```

If grammar is moved to `.tx` file it also works as expected.

**Comment by igordejanovic** [comment]
Also be sure that you are using the latest release as there was a fix in backslash interpretation in string matches. Please see [the changelog](https://github.com/textX/textX/blob/master/CHANGELOG.md).
