### ISSUE TITLE
Grammar extension: catching them all

### ISSUE THREAD

**Issue by pvmm** [textX/textX#382]
I think the following type of attribute capturing would be a good addition to the parser and it comes naturally when we think about what the rules can already do.

`Number: value=( FRACTION | FLOAT | INTEGER )`

instead of having to do this:

`Number: ( value=INTEGER | value=FLOAT | value=FRACTION )
`

**Comment by goto40** [comment]
Thank you for this interesting suggestion. 
 * From an end-user point of view it is a valid extension.
 * From the implementation-of-textx point of view it should be carefully analyzed **what kind of variations are possible and allowed** and what are the consequences of such a change (e.g. is it also allowed to mix references and non-references: `Rule: x=(A | [B]);`?). 
    * @pvmm Maybe the following simple **alternative** is also **acceptable for you?** Define a new rule `FactionOrFloatOrInt: FRACTION | FLOAT | INTEGER;` and use `Number: value=FactionOrFloatOrInt;`. 
    * @igordejanovic Maybe such a transformation could be automated, if we include such an extension.

I think it is not a trivial change...

**Comment by igordejanovic** [comment]
@pvmm Thanks for the suggestion. 

I agree with @goto40. It would be a non-trivial change. Furthermore, if we allow for arbitrary expressions in the RHS of the assignment it would be hard to deduce the meta-model. What would be the meta-class of the RHS for complex expressions? On the other hand, if allowed expressions are somehow constrained it would be difficult to explain those constraint to the end-users. Now it is very simple. You can use only rule references and plain matches (with repetition modifiers for repeatable assignments). I think the way it is now is the best trade-off between the expressive power and the implementation complexity.

I'm closing this issue as `wontfix` but feel free to reopen if you want to discuss further.
