### ISSUE TITLE
Vendored six raises ImportWarning

### ISSUE THREAD

**Issue by davidchall** [textX/textX#390]
I've encountered warnings using textX on Python 3.10, which are caused by the vendored version of six. More details of this issue can be found at: https://github.com/secdev/scapy/issues/3502

**Comment by igordejanovic** [comment]
Thanks for the report. What did you do to trigger the warning?

**Comment by davidchall** [comment]
Any project using textx uses the vendored six module when importing other modules. On Python 3.10+, the vendored version of six throws an ImportWarning when it cannot find a module (before it throws the expected ImportError). This means I cannot use `try: ... except ImportError:` without throwing an ImportWarning.

This problem was fixed in six 1.16.0 (latest version).

```python
import warnings

with warnings.catch_warnings():
    # ensure we notice ImportWarning
    warnings.simplefilter("error", category=ImportWarning)

    # if commented, then vendored six not used and ImportWarning not thrown
    import textx

    try:
        import missing
    except ImportError:
        print("Caught ImportError")
```

**Comment by igordejanovic** [comment]
Thanks for the detailed info. I think now is a good time to remove six as we are not supporting 2.x Python anymore.

**Comment by igordejanovic** [comment]
I plan to release  textX 3.1 in the following days.

**Comment by igordejanovic** [comment]
Version 3.1.0 is released
