### ISSUE TITLE
`pkg_resources` is deprecated

### ISSUE THREAD

**Issue by EmilyBourne** [textX/textX#411]
I am seeing a deprecation warning while using textx:
```
DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
```
The link states:
> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.

This should be fixed to avoid being caught out once the package is fully removed.

I noticed this in a CI test for https://github.com/pyccel/pyccel so I have information about multiple OS/Python version combinations if this is helpful.

## System information
OS: Microsoft Windows Server 2022
Python version : 3.10 installed via miniconda
https://github.com/pyccel/pyccel/actions/runs/6495962235/job/17641938056

Did't reproduce on ubuntu-22.04 with Python versions 3.8, 3.9, 3.10, 3.11
Did't reproduce on macos-12 with Python version 3.10

**Comment by igordejanovic** [comment]
@EmilyBourne Thanks for the heads up.

**Comment by nchammas** [comment]
In Python 3.12, it seems this becomes an error:

```python
$ textx generate demo.tx --target dot
Traceback (most recent call last):
...
  File ".../lib/python3.12/site-packages/textx/registration.py", line 6, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

From the [Python 3.12 release notes][1]:

> [gh-95299](https://github.com/python/cpython/issues/95299): Do not pre-install setuptools in virtual environments created with [venv](https://docs.python.org/dev/library/venv.html#module-venv). This means that distutils, setuptools, pkg_resources, and easy_install will no longer available by default; to access these run pip install setuptools in the [activated](https://docs.python.org/dev/library/venv.html#venv-explanation) virtual environment.


[1]: https://docs.python.org/dev/whatsnew/3.12.html
