### ISSUE TITLE
Migrate examples to `flit_core` as well?

### ISSUE THREAD

**Issue by mgorny** [textX/textX#418]
textX is now using `flit_core` as the primary build system. However, the test projects (`tests/functional/subcommands/example_project` and `tests/functional/registration/projects/*`) all still implicitly use `setuptools`. Could you please consider migrating them as well to use a single build system throughout the project?

**Comment by igordejanovic** [comment]
We should definitely do that. Thanks for reporting.

**Comment by igordejanovic** [comment]
You can test [this branch](https://github.com/textX/textX/compare/fix/flit-core-build)

**Comment by mgorny** [comment]
Thank you. I can confirm that it works, and is much faster (to install the test subprojects) too ;-).

**Comment by igordejanovic** [comment]
Great. I'll release this update shortly.
