### ISSUE TITLE
Support python3.13

### ISSUE THREAD

**Issue by cedric05** [textX/textX#428]
Current/latest version of textx (4.0.1) doesn't support python3.13 (unable to install).

**Comment by stanislaw** [comment]
I opened this: https://github.com/textX/textX/pull/429 but ran into an issue which seems unrelated to Python 3.13.

**Comment by igordejanovic** [comment]
Closed in #429

**Comment by igordejanovic** [comment]
I'll release 4.1.0 shortly.
