### ISSUE TITLE
ImportError: No module named metamodel

### ISSUE THREAD

**Issue by vjrasane** [textX/textX#46]
Installing the latest version with pip does not seem to work anymore. After a fresh installation the following import fails:

from textx.metamodel import metamodel_from_file, metamodel_from_str

with the error:
ImportError: No module named metamodel

At first I thought it could be a configuration problem, but this has occurred on two separate machines.

Or maybe there has been a change in how the imports should be used and I'm not aware of that?

I should also add that I can get around this by downloading the zip and having the library directly in the project that uses it.

**Comment by fgsch** [comment]
Having the same problem. No issues with 1.5.2.

**Comment by aranega** [comment]
On the last version, `metamodel_from_file` and `metamodel_from_str` can be directly imported from `textx`, this should do the trick.

```python
from textx import metamodel_from_file, metamodel_from_str
```

Even if `textx.metamodel` still exists, this line from `__init__.py`: https://github.com/igordejanovic/textX/blob/d742a3fa0d0b535fdada7c9c44017851d3ef522f/textx/__init__.py#L2 
imports `metamodel` from `textx.model` and thus hides the `metamodel` module (at least I assume).

**Comment by igordejanovic** [comment]
There was a problem with the `1.6` build. The wheel I published was invalid. I've just released `1.6.1` which should fix the issue.

**Comment by igordejanovic** [comment]
As @aranega noted `metamodel_from_*` can now be imported directly from `textx` module. The old way is still perfectly valid. That wasn't the issue here though.

**Comment by fgsch** [comment]
@igordejanovic thanks, wfm now.

**Comment by aranega** [comment]
@igordejanovic My bad, I didn't pay well attention to the error message. Indeed, you're right, no issues with the "old" way of importing the function! There is still a kind of "masking" when doing this:

```python
import textx.metamodel

textx.metamodel.metamodel_from_file  # --> raises an AttributeError
```
But I'm aware this is probably not the best way of reaching the function. It still surprised a little bit at first.

**Comment by igordejanovic** [comment]
@aranega Yup. You are right. There is masking of metamodel module by a function of the same name which is a part of model API. I'll see to fix that in the next release. Issue #48 registered.
