### ISSUE TITLE
Refactoring ambiguous rule

### ISSUE THREAD

**Issue by borismarin** [textX/textX#49]
I have been using the following grammar
```
M: defs+= Def; Def: name=ID '=' val+=ID[eolterm];
```
to parse data like
```
a = b
c = d e
f = g
```
I am now trying to rewrite it without having to rely on newlines (`eolterm`) to separate each `Def`. I have been struggling with lookahead predicates to remove ambiguities, to no avail. Any ideas on how to implement that? 

@igordejanovic is there a _textx_ mailing list or some other preferred place for posting 'help requests' like this one, instead of using github issues?

**Comment by igordejanovic** [comment]
You can do this:
```
M: defs += Def;
Def: name=ID '=' val+=Value;
Value: ID !'=';
```
Notice the use of negative lookahead assertion in `Value`.

There is a google group for textX [here](https://groups.google.com/forum/?hl=en#!forum/textx-talk).

**Comment by borismarin** [comment]
Thanks for the quick response - I guess it would be useful to have a link to the mailing list on the [README file](https://github.com/igordejanovic/textX/blob/master/README.rst), so that people like me will stop using issues to get help!
