### ISSUE TITLE
Obj. processor should be able to replace object entirely

### ISSUE THREAD

**Issue by igordejanovic** [textX/textX#64]
This would enable all sorts of additional functionality in a way similar to Arpeggio's visitors or parglare's actions. In addition object processors would replace current functionality of `match filters`.

**Comment by igordejanovic** [comment]
This is implemented in 1.7.0. See [the docs here](http://www.igordejanovic.net/textX/metamodel/#object-processors).

**Comment by goto40** [comment]
Is it possible to register a list of object processors for one rule? The order of execution is defined by the order in the list?

Purpose: multiple validators.
