### ISSUE TITLE
Object processors in rules using assignment with mixed objects

### ISSUE THREAD

**Issue by zilakmarian** [textX/textX#80]
This is linked to issue #72, which looked like it was resolved. But I have found a more complex set of rules that do not work in release 1.7.1 (with #72 fixed), both with python2.7.15 and with python3.6.5.
In release 1.6.1 it works as expected only with python2. Release 1.6.1 with python3 behaves weirdly.

Example code:
```
from textx.metamodel import metamodel_from_str

call_counter = 0
grammar1 = u"""
foo:
    'foo' m_formula = Formula 
;

Formula:
    ( values=FormulaExpression values='+' ( values=FormulaExpression)* )
;

FormulaExpression:
    values=bar
;

bar:
    m_id=/[a-f0-9]+/
;
"""

grammar2 = u"""
foo:
    'foo' m_formula = Formula 
;

Formula:
    ( values=FormulaExpression ( values=FormulaExpression)* )
;

FormulaExpression:
    values=bar
;

bar:
    m_id=/[a-f0-9]+/
;
"""

grammar3 = u"""
foo:
    'foo' m_formula = Formula 
;

Formula:
    ( values=FormulaExpression values='+' ( values=FormulaExpression)* )
;

FormulaExpression:
    values=/[a-f0-9]+/
;

"""

def default_processor(obj):
    global call_counter
    call_counter+= 1
    print("PROCESSING " + str(obj.__class__.__name__))

def parse_str(grammar, lola_str):
    lola_str = str(lola_str)
    obj_processors = {
        "foo": default_processor,
        "Formula": default_processor,
        "FormulaExpression": default_processor,
        "bar": default_processor,
        }

    meta_model = metamodel_from_str(
        grammar, ignore_case=True, auto_init_attributes=False
        )
    meta_model.register_obj_processors(obj_processors)
    model = meta_model.model_from_str(lola_str)
    return model

test_str = u"foo a323 + a111"
call_counter = 0
parse_str(grammar1, test_str)
print(call_counter)  # expecting call_counter == 6
print("---")
test_str = u"foo a323 a111"
call_counter = 0
parse_str(grammar2, test_str)
print(call_counter)
print("---")  # expecting call_counter == 6
test_str = u"foo a323 + a111"
call_counter = 0
parse_str(grammar3, test_str)
print(call_counter)  # expecting call_counter == 4
```

What breaks processors in major way is rule `Formula` which uses assignment with object of different types (textx resolved object and unicode string).
For 1.6.1 with python2 it works as I expected with all three grammars:
`bar`, `Formula`, `FormulaExpression` and `foo` processors are called.
Note in `grammar3` there is no `bar` rule, so only in 'grammar1' and 'grammar2' are expected to call processor for `bar`.

For 1.7.1 with python2
In `grammar2` and `grammar3` processors are called correctly.
But in `grammar1` processor for rule `bar` is not called.

For 1.6.1 and 1.7.1 with python3, `grammar2`  looks like is processed correctly.
Using `grammar1` does not start object processors for rules `FormulaExpression` and `bar`.
Using `grammar3` does not start object processors for rules `FormulaExpression`.

I know textx accepts only unicode so I've used prefix 'u' to enforce unicode be used for grammars and test strings for python2 (this prefix still works in python3). But either way, there seems to be major differences how textx behaves in python2 and python3.

**Comment by igordejanovic** [comment]
Thanks for a detailed report. There has been some recent work on object processors call by @goto40 on #79. That work is not released yet but is merged on master.
I did a quick test and it seems that your example works correctly for both python 2.7 and 3.6. 
Could you test with the current master?
BTW, thanks for the test. I'll incorporate it in the set of unit tests so we will let CI run it for all supported versions.

**Comment by zilakmarian** [comment]
Pulled master, ran the code i posted and it works as expected in python 2.7.15
But in python 3.6.5 it does not. In `grammar1` and `grammar3` processors for rules `FormulaExpression` and `bar` are still not called correctly.
I start to wonder, maybe my code snippet is flawed for python3.

But as long as it works for python2, I'm content and can call this issue resolved.

**Comment by goto40** [comment]
Since the unit test mimics the code above and runs w/o errors we could maybe close this ticket.

Any concerns? We can reopen the ticket if the error comes up again...

**Comment by igordejanovic** [comment]
Agreed. Closing.
