### ISSUE TITLE
model-to-text

### ISSUE THREAD

**Issue by goto40** [textX/textX#90]
Possible new feature:

The inverse function (model-to-text) in addition to model_from_file would allow to use textx as a natural data de/serialization for any application.

It remains open if an existing model file structure and/or comments should remain in some parts when writing back a (possibly modifed) model.

Some details concerning object processors changing model aspects need to be discussed...

**Comment by igordejanovic** [comment]
Agreed. That would be very useful. There has been some discussion on #36.

**Comment by goto40** [comment]
double issue --> see #36
