### ISSUE TITLE
Function model_from_string() returns empty string

### ISSUE THREAD

**Issue by chuiii** [textX/textX#91]
To reproduce:
```
rules = '''
Comments: comment*=Comment ;
Comment: EOLcomment | MLcomment ;
EOLcomment: text=/\/\/.*$/ ;
MLcomment: text=/\/\*(?ms)(.*?)\*\// ;
'''
testStr = '''
// This is end of the line comment
    /* this is 
    multiline 
    comment */
'''
metamodel = metamodel_from_str(rules)
model = metamodel.model_from_str(testStr)
print(model)
```

**Comment by igordejanovic** [comment]
I haven't tested it but `Comment` is a rule with a special semantics. See [here](http://www.igordejanovic.net/textX/latest/grammar/#language-comments). Try to rename it, that should fix your issue. If you are trying to implement comments for your language, that is already supported by textX. Please read the referenced section.

**Comment by chuiii** [comment]
You are right.
I'm really sorry about posting the issue now. I should read docs carefully.

**Comment by igordejanovic** [comment]
@chuiii No problem :)
