### ISSUE TITLE
Bad link in "Multi meta-model support" section

### ISSUE THREAD

**Issue by alensuljkanovic** [textX/textX#95]
Link for tests/test_metamodel/test_multi_metamodel_refs.py. causes 404.

Link can be found in the paragraph that starts with "Referencing elements from another meta model".

**Comment by alensuljkanovic** [comment]
Same link is used in the first use-case.

**Comment by goto40** [comment]
Hello Allen,

Thank you for the feedback.

Until we fix this, here the correct link:
https://github.com/igordejanovic/textX/blob/master/tests/functional/test_metamodel/test_multi_metamodel_refs.py


Alen Suljkanović <notifications@github.com> schrieb am Di., 23. Okt. 2018,
18:15:

**Comment by alensuljkanovic** [comment]
Hello,
You're welcome. I'm familiar with most of the textX source code, so I found a test straightaway. :)

**Comment by goto40** [comment]
Hi,
I fixed the link: See https://github.com/igordejanovic/textX/blob/master/docs/multimetamodel.md
